<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_eicon-close</name>
   <tag></tag>
   <elementGuidId>2136f0e4-e4ad-4b54-a25a-b84a53b0d77b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-popup-modal-2429']/div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dialog-close-button.dialog-lightbox-close-button > i.eicon-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b533c971-4f9a-4299-aa13-f07e93a800c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>eicon-close</value>
      <webElementGuid>a8a19bab-a7b8-4b5a-8e9b-55f15f140cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-popup-modal-2429&quot;)/div[@class=&quot;dialog-widget-content dialog-lightbox-widget-content animated&quot;]/a[@class=&quot;dialog-close-button dialog-lightbox-close-button&quot;]/i[@class=&quot;eicon-close&quot;]</value>
      <webElementGuid>14268cad-46bc-4321-ab10-031b614f1388</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementor-popup-modal-2429']/div/a/i</value>
      <webElementGuid>6d5e9990-f517-4328-b53c-e2cb2f15a00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>0400c014-d3f6-41fd-9018-acf99913a88e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
