<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Squid (band)</name>
   <tag></tag>
   <elementGuidId>89aaf8e9-3330-4e9a-af48-9ea66b605eee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mw-content-ltr.mw-parser-output > ul > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>79b3cb26-6960-4b46-8be0-71183c387c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Squid_(band)</value>
      <webElementGuid>02967547-9e25-45c4-89d2-0ff1f5f793b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Squid (band)</value>
      <webElementGuid>abefdc22-bb50-4af7-bedd-678ff9dc5f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>db519a78-8cc3-4ba7-b7c7-036185cc3fa9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/ul/li/a</value>
      <webElementGuid>8d4eee3b-4109-40bf-ab85-b91077627be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Squid (band)')]</value>
      <webElementGuid>2177e7dd-6c61-4d97-9296-db7f65926cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wiki/Squid_(band)')]</value>
      <webElementGuid>34764d36-16e2-4662-83b9-81b45911fa0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/ul/li/a</value>
      <webElementGuid>e0ca7a1f-6376-4a03-b034-65023f1451a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Squid_(band)' and (text() = 'Squid (band)' or . = 'Squid (band)')]</value>
      <webElementGuid>0500fb39-dbe4-4ed5-8cdb-0828171a6238</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
