<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bird (disambiguation)</name>
   <tag></tag>
   <elementGuidId>240432d9-10be-4aa6-a93d-931c1e90fbb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/div[2]/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mw-disambig</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ab4b9235-b711-4824-80ec-30b0614b0176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Bird_(disambiguation)</value>
      <webElementGuid>416b9e0d-379f-422b-b350-8542dd7271bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mw-disambig</value>
      <webElementGuid>3900f270-e178-4b6b-8c6a-1000497b0d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bird (disambiguation)</value>
      <webElementGuid>75bf7211-c455-4e76-994e-38bd730ffa3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/div[@class=&quot;hatnote navigation-not-searchable&quot;]/span[1]/a[@class=&quot;mw-disambig&quot;]</value>
      <webElementGuid>b2b12cbe-7814-4b82-b59b-dbd9f8af6011</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/div[2]/span/a</value>
      <webElementGuid>2a250cfc-2e3e-4578-b7cc-607bfda50da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bird (disambiguation)')]</value>
      <webElementGuid>b0f8e366-37b0-4392-b4f7-f62e30fc4aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wiki/Bird_(disambiguation)')]</value>
      <webElementGuid>43f98b89-7fa3-4e4e-900b-414145043b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/a</value>
      <webElementGuid>4ff5739f-5da4-43c2-822e-7982a8c5c1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Bird_(disambiguation)' and (text() = 'Bird (disambiguation)' or . = 'Bird (disambiguation)')]</value>
      <webElementGuid>48cc1ab8-5a50-4f3f-a714-c979930769cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
