<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_attachment-medium_large size-medium_lar_18ec5c</name>
   <tag></tag>
   <elementGuidId>001fd8ff-9e62-4817-a1fc-56ded9f49abb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://ohmyhome.com/wp-content/uploads/2024/01/When-Is-the-Best-Time-to-Sell-Your-HDB-Resale-Flat-in-2024-7-768x449.png')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-medium_large.size-medium_large.wp-image-76903.entered.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7360e5ac-993a-4d6d-8684-9e94ead433fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>47ca8810-0130-4c2d-a6e0-febb21ad879f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>a5d9c255-0c65-4e16-9b66-f7dfa60f01c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>640</value>
      <webElementGuid>77787e5f-82a5-4098-8b02-a5c2cb53de24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>374</value>
      <webElementGuid>73475109-51fb-4ff9-9784-21343538d133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ohmyhome.com/wp-content/uploads/2024/01/When-Is-the-Best-Time-to-Sell-Your-HDB-Resale-Flat-in-2024-7-768x449.png</value>
      <webElementGuid>f801d914-09f6-43e1-b57e-197ce52412a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-medium_large size-medium_large wp-image-76903 entered lazyloaded</value>
      <webElementGuid>bdc20e71-3891-4875-9a04-e694fe6adde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-srcset</name>
      <type>Main</type>
      <value>https://ohmyhome.com/wp-content/uploads/2024/01/When-Is-the-Best-Time-to-Sell-Your-HDB-Resale-Flat-in-2024-7-768x449.png 768w, https://ohmyhome.com/wp-content/uploads/2024/01/When-Is-the-Best-Time-to-Sell-Your-HDB-Resale-Flat-in-2024-7-300x175.png 300w, https://ohmyhome.com/wp-content/uploads/2024/01/When-Is-the-Best-Time-to-Sell-Your-HDB-Resale-Flat-in-2024-7.png 813w</value>
      <webElementGuid>e81dfe6e-ec32-4b00-a276-1bc0ccfc6462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-sizes</name>
      <type>Main</type>
      <value>(max-width: 640px) 100vw, 640px</value>
      <webElementGuid>d159d8ac-3e97-421c-8cc8-60c80d5b7987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://ohmyhome.com/wp-content/uploads/2024/01/When-Is-the-Best-Time-to-Sell-Your-HDB-Resale-Flat-in-2024-7-768x449.png</value>
      <webElementGuid>b7d7b53e-935f-4821-9bbf-54e7ec96b5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>a5554c88-4f64-44fe-a048-7270513d72ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 640px) 100vw, 640px</value>
      <webElementGuid>55a6a301-0b26-4e28-89fc-8a7eee259fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://ohmyhome.com/wp-content/uploads/2024/01/When-Is-the-Best-Time-to-Sell-Your-HDB-Resale-Flat-in-2024-7-768x449.png 768w, https://ohmyhome.com/wp-content/uploads/2024/01/When-Is-the-Best-Time-to-Sell-Your-HDB-Resale-Flat-in-2024-7-300x175.png 300w, https://ohmyhome.com/wp-content/uploads/2024/01/When-Is-the-Best-Time-to-Sell-Your-HDB-Resale-Flat-in-2024-7.png 813w</value>
      <webElementGuid>af8d3908-da8b-4195-9a8f-325f28dd7e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-7042 page-parent no-sidebar elementor-default elementor-template-canvas elementor-kit-6 elementor-page elementor-page-7042 elementor-page-51485 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-51485 elementor-location-single post-7042 page type-page status-publish has-post-thumbnail hentry country-en-sg&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-40d7b841 elementor-section-full_width elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-7eacb482&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-2582c8ce elementor-widget elementor-widget-theme-post-content&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor elementor-7042&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-8ce00e2 elementor-section-boxed elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-16e7fa5&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-c7eac3e elementor-grid-tablet-3 blog-feeds-wrapper elementor-grid-3 elementor-grid-mobile-1 elementor-posts--thumbnail-top elementor-widget elementor-widget-posts&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor-posts-container elementor-posts elementor-posts--skin-classic elementor-grid elementor-has-item-ratio&quot;]/article[@class=&quot;elementor-post elementor-grid-item post-76892 post type-post status-publish format-standard has-post-thumbnail hentry category-hdb-blog category-resale-hdb category-en-sg tag-featured tag-hdb-resale tag-hdb-resale-market tag-sell-hdb country-en-sg&quot;]/a[@class=&quot;elementor-post__thumbnail__link&quot;]/div[@class=&quot;elementor-post__thumbnail elementor-fit-height&quot;]/img[@class=&quot;attachment-medium_large size-medium_large wp-image-76903 entered lazyloaded&quot;]</value>
      <webElementGuid>7e20137a-19dc-4a4a-9661-cb3cefeaede7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://ohmyhome.com/wp-content/uploads/2024/01/When-Is-the-Best-Time-to-Sell-Your-HDB-Resale-Flat-in-2024-7-768x449.png')]</value>
      <webElementGuid>e7a19fcd-2e60-47fd-bef8-77f6172f546a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/a/div/img</value>
      <webElementGuid>99d869db-2c58-40ba-9916-07f94adc43a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ohmyhome.com/wp-content/uploads/2024/01/When-Is-the-Best-Time-to-Sell-Your-HDB-Resale-Flat-in-2024-7-768x449.png']</value>
      <webElementGuid>dda51635-0e60-4cde-bf33-54ba5f8f1764</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
