<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Book service</name>
   <tag></tag>
   <elementGuidId>f4183947-0385-49a2-a0d7-c8c3cdac7464</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='en_sg_agent_service_book_docu_banner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#en_sg_agent_service_book_docu_banner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9eac032a-26f3-4c05-820b-9c940bc07eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-button elementor-button-link elementor-size-sm</value>
      <webElementGuid>fab9beba-8e46-4dbc-a911-901427eb7aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ohmyhome.com/en-sg/property-agent-services/book/</value>
      <webElementGuid>58d386d1-4ce8-4cc4-87e4-9fbb3482d201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>en_sg_agent_service_book_docu_banner</value>
      <webElementGuid>49bb68c9-7030-48cf-b245-efb96d5e10d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Book service</value>
      <webElementGuid>db78408b-b0a3-4db5-945d-345b5b0b9833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;en_sg_agent_service_book_docu_banner&quot;)</value>
      <webElementGuid>7849c7f6-6dfb-4cc6-88fd-41fac75790e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='en_sg_agent_service_book_docu_banner']</value>
      <webElementGuid>d3c1437d-5ed9-40a2-bd67-568807c1f83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ohmyhome.com/en-sg/property-agent-services/book/')]</value>
      <webElementGuid>8be60db1-d331-49ec-bc63-a65b2f5ae57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a</value>
      <webElementGuid>b42f3e24-c4d6-4ba3-99d9-85c213d4f7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ohmyhome.com/en-sg/property-agent-services/book/' and @id = 'en_sg_agent_service_book_docu_banner' and (text() = 'Book service' or . = 'Book service')]</value>
      <webElementGuid>90aa5497-5485-4db9-967d-26fbb131f201</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
