<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Microchaetus rappi</name>
   <tag></tag>
   <elementGuidId>da428833-15f4-4883-84db-3cc90af9ce60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/p[3]/i/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(3) > i > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>17be0e6a-0b16-4edf-94fb-ec0516b535d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Microchaetus_rappi</value>
      <webElementGuid>dad1ef93-b361-4161-9c5b-cef380f83cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Microchaetus rappi</value>
      <webElementGuid>798d0f23-0c89-4ca6-9360-6efd54c0e1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/p[3]/i[1]/a[1]</value>
      <webElementGuid>b540e5b2-f803-4706-9356-cfff26904ce5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/p[3]/i/a</value>
      <webElementGuid>3f7e1efc-9fe1-4634-ae1f-fdfb8e1b39db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Microchaetus rappi')]</value>
      <webElementGuid>51217dd2-6cea-4eaf-8fa9-7a8cc8b1544e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wiki/Microchaetus_rappi')]</value>
      <webElementGuid>07195665-9db5-41e0-9734-046a647c0912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/i/a</value>
      <webElementGuid>0078316a-0351-4db8-b5a3-e658020a2251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Microchaetus_rappi' and (text() = 'Microchaetus rappi' or . = 'Microchaetus rappi')]</value>
      <webElementGuid>15f72b05-8710-4dd7-81a2-873d58ab638b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
