<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframewidget2</name>
   <tag></tag>
   <elementGuidId>16397a73-2461-4fc9-939c-d0cfd5a29295</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='widget2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#widget2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ccee9dae-a2ba-40c4-81cf-cd8f4c08aa63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-video</value>
      <webElementGuid>06d52c80-20ee-428b-843f-b524762ea0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f616495f-9752-4369-ba6f-3dae43f686d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share</value>
      <webElementGuid>34e235b8-63a9-4b05-a33d-00470f249053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ohmyhome CEO Explains The Winning Formula To Their Success</value>
      <webElementGuid>c969d74b-7c22-4119-952e-cf3b8d251155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>640</value>
      <webElementGuid>e7cba721-8799-4aa2-b328-45301e8bb425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>360</value>
      <webElementGuid>00c8b411-efcc-484d-9a21-0e3025c7121c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.youtube.com/embed/EOmBdimRxpI?controls=1&amp;rel=0&amp;playsinline=1&amp;modestbranding=0&amp;autoplay=1&amp;enablejsapi=1&amp;origin=https%3A%2F%2Fohmyhome.com&amp;widgetid=1</value>
      <webElementGuid>0fdfa60d-8dcb-4ecc-965a-a39267f790cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>widget2</value>
      <webElementGuid>a6e67c52-3dc3-4ff8-a60d-06b3af84b922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-yt-inspected-18</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2ac9766e-0be4-48d0-9178-850ec63bad97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-yt-inspected-34</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>88239672-7de7-4daa-b5c2-991ee39a902c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;widget2&quot;)</value>
      <webElementGuid>2c1a1ab9-ccb4-4e72-81af-203335477d9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='widget2']</value>
      <webElementGuid>ad683f28-9e6f-4b11-968b-7702b864653d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementor-popup-modal-72561']/div/div[2]/div/section/div/div/div/div/div/div/iframe</value>
      <webElementGuid>de5bf0ad-d85a-4b9a-b9e1-54b06e80d86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/iframe</value>
      <webElementGuid>8af26805-c7d7-4566-9da3-a40c70035372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Ohmyhome CEO Explains The Winning Formula To Their Success' and @src = 'https://www.youtube.com/embed/EOmBdimRxpI?controls=1&amp;rel=0&amp;playsinline=1&amp;modestbranding=0&amp;autoplay=1&amp;enablejsapi=1&amp;origin=https%3A%2F%2Fohmyhome.com&amp;widgetid=1' and @id = 'widget2']</value>
      <webElementGuid>df40933f-77fb-4f7f-bd42-2e5777cc6133</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
