<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_attachment-large size-large wp-image-72_4605bf</name>
   <tag></tag>
   <elementGuidId>5587b158-f2f6-4169-9949-ec8024f594b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://ohmyhome.com/wp-content/uploads/2023/07/rhonda-video-1-1024x711.png')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-large.size-large.wp-image-72621.entered.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7a5d36a6-c462-4854-83e7-56cb40ef7ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>2edc2720-80d4-4888-9f94-f68d27a09050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>ce1b5962-000c-4bd0-9a2d-bdac14e0efb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>640</value>
      <webElementGuid>07e1e97e-3012-4ee6-b13d-125291bd4e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>444</value>
      <webElementGuid>ddaec99f-323a-488e-9d2f-70173683acbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ohmyhome.com/wp-content/uploads/2023/07/rhonda-video-1-1024x711.png</value>
      <webElementGuid>66d75c50-8098-42f5-92a1-9a9b2f6040ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-large size-large wp-image-72621 entered lazyloaded</value>
      <webElementGuid>dc69ca2b-8e38-4b6f-809d-c73ad5ee964e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-srcset</name>
      <type>Main</type>
      <value>https://ohmyhome.com/wp-content/uploads/2023/07/rhonda-video-1-1024x711.png 1024w, https://ohmyhome.com/wp-content/uploads/2023/07/rhonda-video-1-300x208.png 300w, https://ohmyhome.com/wp-content/uploads/2023/07/rhonda-video-1-768x533.png 768w, https://ohmyhome.com/wp-content/uploads/2023/07/rhonda-video-1.png 1200w</value>
      <webElementGuid>3d0460a8-6ad8-4b75-af4e-a69c52f8e4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-sizes</name>
      <type>Main</type>
      <value>(max-width: 640px) 100vw, 640px</value>
      <webElementGuid>5f7732df-8b33-4f08-bc97-30bdb90e853b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://ohmyhome.com/wp-content/uploads/2023/07/rhonda-video-1-1024x711.png</value>
      <webElementGuid>bd0d37d5-974c-4a80-af89-16129f14db26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>8f25cb91-c567-4ad7-a2fc-abd6d1b59c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 640px) 100vw, 640px</value>
      <webElementGuid>b1688b13-b8fc-4f33-8527-c627a52e949b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://ohmyhome.com/wp-content/uploads/2023/07/rhonda-video-1-1024x711.png 1024w, https://ohmyhome.com/wp-content/uploads/2023/07/rhonda-video-1-300x208.png 300w, https://ohmyhome.com/wp-content/uploads/2023/07/rhonda-video-1-768x533.png 768w, https://ohmyhome.com/wp-content/uploads/2023/07/rhonda-video-1.png 1200w</value>
      <webElementGuid>152abd0d-7a33-486f-b64a-12c87ba732b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-57031 page-child parent-pageid-7077 no-sidebar elementor-default elementor-template-canvas elementor-kit-6 elementor-page elementor-page-57031 elementor-page-51485 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-51485 elementor-location-single post-57031 page type-page status-publish hentry country-en-sg&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-40d7b841 elementor-section-full_width elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-7eacb482&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-2582c8ce elementor-widget elementor-widget-theme-post-content&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor elementor-57031&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-7e104e7 elementor-section-content-middle elementor-section-boxed elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-5674679&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/section[@class=&quot;elementor-section elementor-inner-section elementor-element elementor-element-fe6d75a elementor-section-boxed elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-50 elementor-inner-column elementor-element elementor-element-7ec69de banner-video-video-container&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-787f89d elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/a[1]/img[@class=&quot;attachment-large size-large wp-image-72621 entered lazyloaded&quot;]</value>
      <webElementGuid>ca670152-7218-4d03-b62c-35d36a3fb465</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://ohmyhome.com/wp-content/uploads/2023/07/rhonda-video-1-1024x711.png')]</value>
      <webElementGuid>90eeb46e-0f10-40f9-8b60-4d7146bfacd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>31a2105e-b06d-4d0e-afc0-d4cf4e611bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ohmyhome.com/wp-content/uploads/2023/07/rhonda-video-1-1024x711.png']</value>
      <webElementGuid>2c6251b4-74fd-4af8-a161-93947413446a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
