<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Office</name>
   <tag></tag>
   <elementGuidId>eda8ebbc-ed45-4b55-bb25-f3af905efd78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='office-dreamr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#office-dreamr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>51a189eb-98bf-46d5-a1fd-8ed1f5b8bfe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>office-dreamr</value>
      <webElementGuid>ec5facd6-72cf-4f93-abce-526d3725aa07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/office-renovation</value>
      <webElementGuid>2e120c66-2045-4c0b-a073-8b8b257b8484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dreamr-nav-link</value>
      <webElementGuid>37aebed5-6bf0-4c5b-a249-a9d4a1a77592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Office</value>
      <webElementGuid>1ea22e51-0615-4e5c-9be3-51869058a044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;office-dreamr&quot;)</value>
      <webElementGuid>8dfac291-5ec3-4634-987d-3776269fa03d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='office-dreamr']</value>
      <webElementGuid>e855e9d4-1c40-47b7-bed9-28f5d89cf0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-node-fb80a31e-1f23-6a5c-b0af-23716be69ae1-f987ae03']/a</value>
      <webElementGuid>5a77024d-a491-44ab-82ae-cd3dd948908a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Office')]</value>
      <webElementGuid>1bf1a30b-f818-42c5-8cf6-795f847c4786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/office-renovation')]</value>
      <webElementGuid>20fc5010-17ac-482b-a25e-4dcededb64e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>54104594-da3a-48e5-be57-7bfb28dfda9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'office-dreamr' and @href = '/office-renovation' and (text() = 'Office' or . = 'Office')]</value>
      <webElementGuid>9692310e-0496-4afb-b9d9-846b02701bd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
