<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Indonesia</name>
   <tag></tag>
   <elementGuidId>fb4c9ad7-5c31-4a3b-ab16-f8efd7f1dd21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/p[2]/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(2) > a:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2c072466-6e57-4f6d-8164-aa13601a6592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Indonesia</value>
      <webElementGuid>bcd6ef67-8a4b-4459-a7aa-c53df6d94444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia</value>
      <webElementGuid>501f9d76-51a7-4d22-aed7-53eba0673fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/p[2]/a[3]</value>
      <webElementGuid>ce900f45-c0a1-4ac1-877b-de3a6102b9b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/p[2]/a[3]</value>
      <webElementGuid>1fb3bcc9-e237-4707-bd56-0d9f1ec09c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Indonesia')])[10]</value>
      <webElementGuid>98e032c9-b37a-418a-a2a2-78312c6a585d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/wiki/Indonesia')])[16]</value>
      <webElementGuid>a11880ef-d4d7-45ec-925b-82d8ea8d815b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a[3]</value>
      <webElementGuid>3177fb74-0ced-49f8-8b39-eb2df784c8ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Indonesia' and (text() = 'Indonesia' or . = 'Indonesia')]</value>
      <webElementGuid>81867cb1-a000-4f20-b6ea-40d20f108183</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
