<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Id like to rent a placeId like to buy a propertyId like to sell my homeId like to rent a place</name>
   <tag></tag>
   <elementGuidId>1d551eb0-34fb-4da4-bbef-9f37f7290d85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='intercom-container']/div/div/div[2]/div/div/div[2]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.intercom-1giwv7k.eqq3twc3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>be426fec-e5b4-4f88-95d8-dbe5dc2a21ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>144</value>
      <webElementGuid>606f73cd-6bcd-4f4d-9f3d-64f191266d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>intercom-1giwv7k eqq3twc3</value>
      <webElementGuid>76745d38-cafe-45ab-b1df-2b56cc06bc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I'd like to rent a placeI'd like to buy a propertyI'd like to sell my homeI'd like to rent a place</value>
      <webElementGuid>0435e7cd-500c-4b7a-9f78-b2e852421389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;intercom-container&quot;)/div[1]/div[@class=&quot;intercom-borderless intercom-d0vrff e13xul2n0&quot;]/div[@class=&quot;intercom-85xkxk e13xul2n1&quot;]/div[@class=&quot;intercom-1i8xzbe emfaaq10&quot;]/div[@class=&quot;intercom-1imlk2a emfaaq11&quot;]/div[@class=&quot;intercom-ewx31z edyhj2e0&quot;]/div[1]/div[@class=&quot;composer-suggestions-container intercom-6uzfmy eqq3twc0&quot;]/div[@class=&quot;intercom-xbrvud eqq3twc2&quot;]/div[@class=&quot;intercom-1giwv7k eqq3twc3&quot;]</value>
      <webElementGuid>81d220a3-dbb1-453c-9cf7-f86c91594470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Affordable Houses and Lots for Sale 20_1a8e84/iframe_intercom-borderless-frame</value>
      <webElementGuid>c141a864-7e47-4d21-be55-508fada9042a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='intercom-container']/div/div/div[2]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>b4e5cbf6-6eab-4ca6-99e5-c10fca6be8c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>b0eebe5e-d43c-41d8-8432-32e1fe0bbdfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;I&quot; , &quot;'&quot; , &quot;d like to rent a placeI&quot; , &quot;'&quot; , &quot;d like to buy a propertyI&quot; , &quot;'&quot; , &quot;d like to sell my homeI&quot; , &quot;'&quot; , &quot;d like to rent a place&quot;) or . = concat(&quot;I&quot; , &quot;'&quot; , &quot;d like to rent a placeI&quot; , &quot;'&quot; , &quot;d like to buy a propertyI&quot; , &quot;'&quot; , &quot;d like to sell my homeI&quot; , &quot;'&quot; , &quot;d like to rent a place&quot;))]</value>
      <webElementGuid>f068e01e-c51c-4e1f-b5a4-b70d58fbd85e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
