<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_intercom-borderless-frame</name>
   <tag></tag>
   <elementGuidId>0aa8c4d3-38b2-44f7-8caa-ded5c5879ac1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='intercom-borderless-frame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;intercom-borderless-frame&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>1490e2ee-3997-48bd-94e0-f5bbc53f585e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>intercom-borderless-frame intercom-f5h638 e1dl9bzv0</value>
      <webElementGuid>c8de8b97-1b79-42bc-9b19-36139db70deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>intercom-borderless-frame</value>
      <webElementGuid>9708238c-d416-4016-a85e-d7711873bac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Intercom live chat message</value>
      <webElementGuid>1958eacd-9f3f-4404-90dd-1f095463352a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-intercom-frame</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d81daf01-2275-4241-9303-60e81ccabff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>522ba789-874c-4714-96d6-120d6a8c4fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;intercom-container&quot;)/div[@class=&quot;intercom-app&quot;]/div[2]/iframe[@class=&quot;intercom-borderless-frame intercom-f5h638 e1dl9bzv0&quot;]</value>
      <webElementGuid>72cfce4c-115d-4b9e-8fe6-3a4daef3951e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='intercom-borderless-frame']</value>
      <webElementGuid>0a54a60e-a37c-4ee9-949e-db350784bbd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='intercom-container']/div/div[2]/iframe</value>
      <webElementGuid>ee13c720-a762-4904-917f-ee78ec8e297d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>71986caf-2b9a-4945-9d58-cdc08a37107b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'intercom-borderless-frame' and @title = 'Intercom live chat message']</value>
      <webElementGuid>c9bd2600-571f-4526-83b4-02d713c751dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
