<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_skip-lazy_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>3b923889-7998-40f6-a09f-b60cb868c9be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='n2-ss-46']/div/div[2]/div/div/div/div[10]/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.n2-thumbnail-dot.n2-style-38b8ce91c93cc0939916bc91c03d5b00-dot.n2-active > picture.skip-lazy > img.skip-lazy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9ed1acf8-eb3c-4b00-b50a-27b3da759c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>21be1179-bae3-4e0e-b4bd-b61a7e158f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>33e23ffc-8ee2-4e37-b8d5-17e1b19cde84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Amoa</value>
      <webElementGuid>548c711f-7d25-4cc1-a7fa-003278e24ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//ohmyhome.com/wp-content/uploads/2022/07/AMOA.png</value>
      <webElementGuid>136fc32e-91d0-4212-b127-819bc68fab73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>ca8c43ca-a552-4304-b402-23c535590211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1125</value>
      <webElementGuid>afba9fea-241c-4342-ba74-32f61627ab72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>skip-lazy</value>
      <webElementGuid>96b82334-9350-4bc3-b996-d722b75af3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-skip-lazy</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fbfa162e-ca2d-4ed6-9ff3-446d838efe4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n2-ss-46&quot;)/div[@class=&quot;n2-ss-slider-wrapper-outside&quot;]/div[@class=&quot;n2-ss-slider-controls n2-ss-slider-controls-below&quot;]/div[@class=&quot;n2-ss-widget nextend-thumbnail nextend-thumbnail-default nextend-thumbnail-horizontal n2-ow-all&quot;]/div[@class=&quot;nextend-thumbnail-inner n2-style-e6db4dc3fb869a4fd58dcf4ad6d79d31-simple&quot;]/div[@class=&quot;nextend-thumbnail-scroller n2-align-content-center&quot;]/div[@class=&quot;n2-thumbnail-dot n2-style-38b8ce91c93cc0939916bc91c03d5b00-dot n2-active&quot;]/picture[@class=&quot;skip-lazy&quot;]/img[@class=&quot;skip-lazy&quot;]</value>
      <webElementGuid>de41acc7-c90f-4fa2-9931-2dbee6cf9985</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='n2-ss-46']/div/div[2]/div/div/div/div[10]/picture/img</value>
      <webElementGuid>86e09414-2bde-437f-8838-3cdd27648c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Amoa']</value>
      <webElementGuid>f015f228-f000-40f2-8526-2e8f121f5add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/picture/img</value>
      <webElementGuid>49f6adc5-d02f-4572-8f97-10dcf3100fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Amoa' and @src = '//ohmyhome.com/wp-content/uploads/2022/07/AMOA.png']</value>
      <webElementGuid>8f8c05e8-5cf4-45c4-bfb9-d472080d11dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
