<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_skip-lazy_1_2_3</name>
   <tag></tag>
   <elementGuidId>c1e5d2c1-890e-4e12-b56a-e7c925f1f84a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='n2-ss-46']/div/div[2]/div/div/div/div[6]/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.n2-thumbnail-dot.n2-style-38b8ce91c93cc0939916bc91c03d5b00-dot.n2-active > picture.skip-lazy > img.skip-lazy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b2a74cfe-b154-402f-9d23-899f178549f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>b88bbfab-ca70-45ca-8151-f8c970f93b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>c9440ba2-80c8-4c69-9a9f-9f7fd1dfb5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>3Torre Lorenzo</value>
      <webElementGuid>7f563062-9a55-4a21-bc66-0e419898abbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//ohmyhome.com/wp-content/uploads/2022/07/3Torre-Lorenzo.png</value>
      <webElementGuid>8b49580d-5060-4d4c-98b7-990927bd3557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>ef64c6c6-956a-41e7-b2e6-7e2f19df09c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1125</value>
      <webElementGuid>24910783-827d-4f02-b906-e50ca931d9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>skip-lazy</value>
      <webElementGuid>15d4753d-979b-416e-9a8c-cc510bb9f955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-skip-lazy</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5bede885-24b9-4602-b3bb-d6f01c3f4842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n2-ss-46&quot;)/div[@class=&quot;n2-ss-slider-wrapper-outside&quot;]/div[@class=&quot;n2-ss-slider-controls n2-ss-slider-controls-below&quot;]/div[@class=&quot;n2-ss-widget nextend-thumbnail nextend-thumbnail-default nextend-thumbnail-horizontal n2-ow-all&quot;]/div[@class=&quot;nextend-thumbnail-inner n2-style-e6db4dc3fb869a4fd58dcf4ad6d79d31-simple&quot;]/div[@class=&quot;nextend-thumbnail-scroller n2-align-content-center&quot;]/div[@class=&quot;n2-thumbnail-dot n2-style-38b8ce91c93cc0939916bc91c03d5b00-dot n2-active&quot;]/picture[@class=&quot;skip-lazy&quot;]/img[@class=&quot;skip-lazy&quot;]</value>
      <webElementGuid>249a47f4-e0fb-4d08-8353-e80699bcd503</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='n2-ss-46']/div/div[2]/div/div/div/div[6]/picture/img</value>
      <webElementGuid>c226f688-fd69-40fe-b615-cb21ee62c0b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='3Torre Lorenzo']</value>
      <webElementGuid>91aff6e1-b739-490f-a729-654e8a5a4293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/picture/img</value>
      <webElementGuid>e81969fe-4f0f-4435-9105-644c28bb3d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = '3Torre Lorenzo' and @src = '//ohmyhome.com/wp-content/uploads/2022/07/3Torre-Lorenzo.png']</value>
      <webElementGuid>1f3c593b-d637-46ed-89d5-c507a6d1d7ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
