<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_skip-lazy_1_2</name>
   <tag></tag>
   <elementGuidId>452ece5a-46fc-4b64-af68-8b56086d96c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='n2-ss-46']/div/div[2]/div/div/div/div[4]/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.n2-thumbnail-dot.n2-style-38b8ce91c93cc0939916bc91c03d5b00-dot.n2-active > picture.skip-lazy > img.skip-lazy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9a78035f-2369-49f9-9d3b-c46581be45e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>5fd958f9-8984-4cbc-8a20-2592ec09b2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>6bfd9a33-8d2a-4c7a-906f-fc6dd28b8291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>The Velaris Residences</value>
      <webElementGuid>c7d5913c-5a91-452f-aee5-57ee0f0d8ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//ohmyhome.com/wp-content/uploads/2022/07/Velaris.png</value>
      <webElementGuid>4af2e1b4-74e4-42c5-9337-3587b2ea1c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>ce393ca2-515f-4193-a130-eed9eae93b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1125</value>
      <webElementGuid>5af57fac-aa2c-4d52-bf98-9381b37fc0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>skip-lazy</value>
      <webElementGuid>96e68c1a-9d31-45d7-b438-d9b95099bd7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-skip-lazy</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c4172710-e14f-406b-8ff5-51e567d516b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n2-ss-46&quot;)/div[@class=&quot;n2-ss-slider-wrapper-outside&quot;]/div[@class=&quot;n2-ss-slider-controls n2-ss-slider-controls-below&quot;]/div[@class=&quot;n2-ss-widget nextend-thumbnail nextend-thumbnail-default nextend-thumbnail-horizontal n2-ow-all&quot;]/div[@class=&quot;nextend-thumbnail-inner n2-style-e6db4dc3fb869a4fd58dcf4ad6d79d31-simple&quot;]/div[@class=&quot;nextend-thumbnail-scroller n2-align-content-center&quot;]/div[@class=&quot;n2-thumbnail-dot n2-style-38b8ce91c93cc0939916bc91c03d5b00-dot n2-active&quot;]/picture[@class=&quot;skip-lazy&quot;]/img[@class=&quot;skip-lazy&quot;]</value>
      <webElementGuid>037b13c0-bb02-4dd4-9db6-4dca3c4068a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='n2-ss-46']/div/div[2]/div/div/div/div[4]/picture/img</value>
      <webElementGuid>7a5d6465-f6b9-44a9-ac65-f59e447f4d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='The Velaris Residences']</value>
      <webElementGuid>75a4de7e-cf7f-4640-aa84-f9bbaa744220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/picture/img</value>
      <webElementGuid>5e463133-8c56-4bd7-aa82-480b487c1144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'The Velaris Residences' and @src = '//ohmyhome.com/wp-content/uploads/2022/07/Velaris.png']</value>
      <webElementGuid>f222736c-f353-4788-9543-f4efb67c1f9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
