<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_skip-lazy_1_2_3_4_5_6_7_8</name>
   <tag></tag>
   <elementGuidId>22aade0e-71dc-407a-9b4e-6af1fddd6933</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='n2-ss-46']/div/div[2]/div/div/div/div[11]/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.n2-thumbnail-dot.n2-style-38b8ce91c93cc0939916bc91c03d5b00-dot.n2-active > picture.skip-lazy > img.skip-lazy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d28d3541-9d83-41d9-b748-e104d1ee9d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>05ca8a4d-2c6d-42ec-acfc-3cf9eb4c2475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>aaa036ed-7ca4-443e-bfba-047e87ab5965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sands Residences</value>
      <webElementGuid>6fb02211-5086-4019-8411-7ee49654745d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//ohmyhome.com/wp-content/uploads/2022/07/SANDS-Residences.png</value>
      <webElementGuid>847f64d9-48f0-4858-a1a3-f8f338c08de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>3c47228e-3660-4ef9-89ff-30020e942478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1125</value>
      <webElementGuid>5b16d215-2fc2-43f3-b937-b887da280eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>skip-lazy</value>
      <webElementGuid>04ef9ada-b912-4e7c-a720-a5171b3b643d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-skip-lazy</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cdd3d97f-84e4-43ae-b86e-ea5b5e862d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n2-ss-46&quot;)/div[@class=&quot;n2-ss-slider-wrapper-outside&quot;]/div[@class=&quot;n2-ss-slider-controls n2-ss-slider-controls-below&quot;]/div[@class=&quot;n2-ss-widget nextend-thumbnail nextend-thumbnail-default nextend-thumbnail-horizontal n2-ow-all&quot;]/div[@class=&quot;nextend-thumbnail-inner n2-style-e6db4dc3fb869a4fd58dcf4ad6d79d31-simple&quot;]/div[@class=&quot;nextend-thumbnail-scroller n2-align-content-center&quot;]/div[@class=&quot;n2-thumbnail-dot n2-style-38b8ce91c93cc0939916bc91c03d5b00-dot n2-active&quot;]/picture[@class=&quot;skip-lazy&quot;]/img[@class=&quot;skip-lazy&quot;]</value>
      <webElementGuid>86aaffe4-a9c2-4cf3-a365-3ec60614339d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='n2-ss-46']/div/div[2]/div/div/div/div[11]/picture/img</value>
      <webElementGuid>a15628fd-f06b-42f8-80ff-dc597ca0c552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sands Residences']</value>
      <webElementGuid>1adf413c-b8cf-4f96-b0f2-d1717ae5ef74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/picture/img</value>
      <webElementGuid>f7ce4cc2-4c0e-4965-b1c6-54f2a4695399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Sands Residences' and @src = '//ohmyhome.com/wp-content/uploads/2022/07/SANDS-Residences.png']</value>
      <webElementGuid>811450e3-b88b-49af-9faf-5d2e7f6c802c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
