<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_skip-lazy</name>
   <tag></tag>
   <elementGuidId>ecd608eb-d414-4142-834f-70ff6f107675</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='n2-ss-46']/div/div[2]/div/div/div/div[2]/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.n2-thumbnail-dot.n2-style-38b8ce91c93cc0939916bc91c03d5b00-dot.n2-active > picture.skip-lazy > img.skip-lazy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2ac515bf-4b39-455d-8d13-8934ffed25fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>9bdf1d7c-86cf-4d45-a223-6a816ce7629e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>a1bf85d0-16bc-4d0d-854e-26314a5f8c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Amaia Series Vermosa</value>
      <webElementGuid>31697005-9efe-4057-b00a-5cfce43e8782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//ohmyhome.com/wp-content/uploads/2022/07/Amaia-Series-Vermosa-1-1.png</value>
      <webElementGuid>9277cb31-2c07-4285-92ae-beb04a2ca63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>99b6902a-e24f-4bd6-a75a-42eff780a5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1125</value>
      <webElementGuid>01082397-d22f-4d9f-bc38-b2b9f2dbebd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>skip-lazy</value>
      <webElementGuid>4e065b80-423f-49e5-80b3-cdc39e30e131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-skip-lazy</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>08146858-e462-40e8-ae21-a65b412ea12a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n2-ss-46&quot;)/div[@class=&quot;n2-ss-slider-wrapper-outside&quot;]/div[@class=&quot;n2-ss-slider-controls n2-ss-slider-controls-below&quot;]/div[@class=&quot;n2-ss-widget nextend-thumbnail nextend-thumbnail-default nextend-thumbnail-horizontal n2-ow-all&quot;]/div[@class=&quot;nextend-thumbnail-inner n2-style-e6db4dc3fb869a4fd58dcf4ad6d79d31-simple&quot;]/div[@class=&quot;nextend-thumbnail-scroller n2-align-content-center&quot;]/div[@class=&quot;n2-thumbnail-dot n2-style-38b8ce91c93cc0939916bc91c03d5b00-dot n2-active&quot;]/picture[@class=&quot;skip-lazy&quot;]/img[@class=&quot;skip-lazy&quot;]</value>
      <webElementGuid>bd84c536-0987-472e-8926-48ed9f8e8938</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='n2-ss-46']/div/div[2]/div/div/div/div[2]/picture/img</value>
      <webElementGuid>a364afa6-dbc0-489c-832d-ff00b824e5f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Amaia Series Vermosa']</value>
      <webElementGuid>a030f758-2d5a-4f8e-9292-549cbb06dd10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/picture/img</value>
      <webElementGuid>7032ae5a-eea4-4299-834f-91ef2c73f0a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Amaia Series Vermosa' and @src = '//ohmyhome.com/wp-content/uploads/2022/07/Amaia-Series-Vermosa-1-1.png']</value>
      <webElementGuid>6c4d2bad-08e7-4290-8ba6-cabcc1f9d76e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
