<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Book an agent</name>
   <tag></tag>
   <elementGuidId>0b6bb504-1ae0-4c2c-b77c-35c030ca5052</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='en_ph_banner_book_agent_hero']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#en_ph_banner_book_agent_hero</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6e84c8c1-fd2b-4c31-8da6-1174e26f8f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-button elementor-button-link elementor-size-sm</value>
      <webElementGuid>b38876e5-36f1-43d9-b9ac-845328cd570b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ohmyhome.com/en-ph/contact-us/</value>
      <webElementGuid>dc56bf83-fdb4-4b1c-946b-f76467f8ddf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>en_ph_banner_book_agent_hero</value>
      <webElementGuid>c58919b9-75d1-4352-9fdb-e7769139bb67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Book an agent</value>
      <webElementGuid>39d3fc71-0cc7-4975-9939-a6188073a9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;en_ph_banner_book_agent_hero&quot;)</value>
      <webElementGuid>2abcfff3-c233-4aa4-a642-f0c47d35711c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='en_ph_banner_book_agent_hero']</value>
      <webElementGuid>b41d623f-295d-4c37-a07d-f15d45e0ec6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ohmyhome.com/en-ph/contact-us/')]</value>
      <webElementGuid>191fd937-e5db-44fe-acb1-65c16dce9fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]/div/div/a</value>
      <webElementGuid>26c23523-75fb-44e7-8ed5-6fb275906e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ohmyhome.com/en-ph/contact-us/' and @id = 'en_ph_banner_book_agent_hero' and (text() = 'Book an agent' or . = 'Book an agent')]</value>
      <webElementGuid>4cf8ea61-cd53-48da-a734-796a9b800e8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
