<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Consult our agents</name>
   <tag></tag>
   <elementGuidId>29f25bee-e9da-4456-a067-081d75177427</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='en_ph_banner_book_agent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#en_ph_banner_book_agent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>882f60ef-c819-4853-a29f-96f9f1237c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-button elementor-button-link elementor-size-sm</value>
      <webElementGuid>a51ae9d5-9b9e-47a3-935b-8080ecfe1e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://m.me/ohmyhomeph</value>
      <webElementGuid>60e3d6f6-bd99-49bb-ba8f-44adeb7f9bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>en_ph_banner_book_agent</value>
      <webElementGuid>bf55ec05-e5b8-4520-8ccf-a561e1326cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Consult our agents</value>
      <webElementGuid>3040fe4b-a5d8-4f00-a270-ba71ebcb89f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;en_ph_banner_book_agent&quot;)</value>
      <webElementGuid>57dacd91-bf3c-46bd-a883-15dd1f694b46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='en_ph_banner_book_agent']</value>
      <webElementGuid>c5e80aab-a3c6-4cea-a2a6-78cbe381dcdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://m.me/ohmyhomeph')])[4]</value>
      <webElementGuid>103694d1-973a-4887-a2a2-d11ecc045734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div[4]/div/div/a</value>
      <webElementGuid>954f8a99-98f8-4d33-b598-92d44c84c493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://m.me/ohmyhomeph' and @id = 'en_ph_banner_book_agent' and (text() = 'Consult our agents' or . = 'Consult our agents')]</value>
      <webElementGuid>b744ce49-ecbd-4927-a9d5-aed221ee1204</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
