<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_View more articles</name>
   <tag></tag>
   <elementGuidId>9d01ae70-7a0c-4ece-b971-3483e5e1cc88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='en_sg_agent_service_view_more_articles']/span/span)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.elementor-element.elementor-element-5027b89.elementor-align-center.elementor-mobile-align-center.elementor-widget.elementor-widget-button > div.elementor-widget-container > div.elementor-button-wrapper > #en_sg_agent_service_view_more_articles > span.elementor-button-content-wrapper > span.elementor-button-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>940a13b2-e66d-40fc-8cd4-033560f25f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-button-text</value>
      <webElementGuid>0122e39e-535c-46eb-8ec5-4a75fde69a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View more articles</value>
      <webElementGuid>2ec01891-0374-4a7b-a522-e3f93bededaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-7077 page-parent page-child parent-pageid-7042 no-sidebar elementor-default elementor-template-canvas elementor-kit-6 elementor-page elementor-page-7077 elementor-page-51485 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-51485 elementor-location-single post-7077 page type-page status-publish hentry country-en-sg&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-40d7b841 elementor-section-full_width elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-7eacb482&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-2582c8ce elementor-widget elementor-widget-theme-post-content&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor elementor-7077&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-7ed20bb7 elementor-section-boxed elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-17f6cd13&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-5027b89 elementor-align-center elementor-mobile-align-center elementor-widget elementor-widget-button&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor-button-wrapper&quot;]/a[@id=&quot;en_sg_agent_service_view_more_articles&quot;]/span[@class=&quot;elementor-button-content-wrapper&quot;]/span[@class=&quot;elementor-button-text&quot;]</value>
      <webElementGuid>1bcc602f-ad1f-4b9f-965c-5fd9567ef4e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='en_sg_agent_service_view_more_articles']/span/span)[2]</value>
      <webElementGuid>36a10e21-a05f-478d-bca8-6cd9da66f8f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/a/span/span</value>
      <webElementGuid>1a6db2a3-d039-4b5b-8ab5-f79d286a26f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'View more articles' or . = 'View more articles')]</value>
      <webElementGuid>37fb2eea-788c-4096-8304-fe236accab0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
