<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sell with us</name>
   <tag></tag>
   <elementGuidId>55756fb0-3486-4536-aaa3-fa0ea0f81ae3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='weve-sold-homer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#weve-sold-homer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>02d78164-1b5c-41f2-bf2f-8699d94693b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ohmyhome.com/en-sg/property-agent-services/book-an-agent/?utm_source=ads&amp;utm_campaign=property-valuation</value>
      <webElementGuid>7331ff0f-0c5e-4d36-8f1d-82e98303e5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>weve-sold-homer</value>
      <webElementGuid>3ffa517e-c45b-4f69-b3f9-ade00bf2b09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>2784cfab-09d3-4dda-9325-2d86560e47d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button main-cta w-button</value>
      <webElementGuid>f19134ea-4748-4e71-8f29-bc1354a4f35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sell with us</value>
      <webElementGuid>e12d9443-efcb-4ec6-a81e-84da7048f422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;weve-sold-homer&quot;)</value>
      <webElementGuid>d4e6ddd3-ca8d-45e0-81ab-6b7bf51d657f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='weve-sold-homer']</value>
      <webElementGuid>654dff0d-6dc2-4109-a440-199a69c0d1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-node-_38390562-d6b6-f7ce-4847-1fed243c8b81-a933941a']/a</value>
      <webElementGuid>8af15f8b-928f-44f0-bf95-0734b2131aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Sell with us')])[2]</value>
      <webElementGuid>0cc3dd09-ea61-41e5-971a-5d6ac0c64602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://ohmyhome.com/en-sg/property-agent-services/book-an-agent/?utm_source=ads&amp;utm_campaign=property-valuation')])[2]</value>
      <webElementGuid>9be655b7-2652-4fbf-9d5c-c62b4d79ab50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>24378b57-7378-46a8-96cc-a693c152a502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ohmyhome.com/en-sg/property-agent-services/book-an-agent/?utm_source=ads&amp;utm_campaign=property-valuation' and @id = 'weve-sold-homer' and (text() = 'Sell with us' or . = 'Sell with us')]</value>
      <webElementGuid>5f68586d-233a-4dd5-b8ed-104e83e68bf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
