<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Contact</name>
   <tag></tag>
   <elementGuidId>4944ae58-9119-4fe6-aecc-4f7d7e98501d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Contact')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f384f744-839f-4adc-aea5-c9008e4320e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en-ph/contact-us/</value>
      <webElementGuid>a25781b5-91f7-4149-97ac-40fdf03ed248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>omh-footer-menu-tracking</value>
      <webElementGuid>d7e6e1ab-4754-433b-9bd8-1384d01987f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text</name>
      <type>Main</type>
      <value>Contact</value>
      <webElementGuid>eec173ca-21f1-47d3-815b-632e0ef35665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Contact </value>
      <webElementGuid>9d84d821-59a3-400f-90ce-2e0fb06d5b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-10201 page-child parent-pageid-7046 no-sidebar elementor-default elementor-template-canvas elementor-kit-6 elementor-page elementor-page-10201 elementor-page-51482 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-51482 elementor-location-single post-10201 page type-page status-publish hentry country-en-ph&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-3abfbd5 elementor-section-full_width hide-during-webview elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-9a12298&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-1b52a17 elementor-widget elementor-widget-footer&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;footer-wrapper&quot;]/div[@class=&quot;footer-container&quot;]/div[@class=&quot;footer-middle-col&quot;]/div[@class=&quot;footer-menu-wrapper&quot;]/div[@class=&quot;footer-menu-block&quot;]/div[@class=&quot;footer-menu-item-container&quot;]/div[@class=&quot;footer-menu-item&quot;]/a[@class=&quot;omh-footer-menu-tracking&quot;]</value>
      <webElementGuid>c9756634-018a-480e-a73e-e37312d9673a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Contact')]</value>
      <webElementGuid>4e14b994-df6c-49e9-ae73-c660258d1c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/en-ph/contact-us/')])[5]</value>
      <webElementGuid>938eda2a-7f16-4a1a-845f-e93c13479266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a</value>
      <webElementGuid>399fd3b8-0b4a-47fa-822a-cfecfa7934d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en-ph/contact-us/' and (text() = ' Contact ' or . = ' Contact ')]</value>
      <webElementGuid>f8d42f6c-fb2f-4df8-84da-da99d581baec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
