<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Alligator</name>
   <tag></tag>
   <elementGuidId>4e85a0c7-4991-4528-95d0-ea9626e3b3e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.hatnote.navigation-not-searchable > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d694e74-aeab-4fbe-a2e3-adf9c3c836de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Alligator_(film)</value>
      <webElementGuid>85f22fef-105e-4aa5-9de0-f4d00be6634f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alligator</value>
      <webElementGuid>87db7b43-a928-49e8-ab4d-0711daebc3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/div[@class=&quot;hatnote navigation-not-searchable&quot;]/a[1]</value>
      <webElementGuid>fc7866f7-72d5-4acc-9c2e-f47520e74088</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/div/a</value>
      <webElementGuid>582303f7-24f3-4338-a19e-5bde2e713508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Alligator')]</value>
      <webElementGuid>6b92a488-a712-4e5c-9f0f-8aeca592c9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wiki/Alligator_(film)')]</value>
      <webElementGuid>443d9f0b-5c3a-4d48-ab36-ad8082bc3915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/a</value>
      <webElementGuid>f86aac73-650b-4398-a165-d21a5b145d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Alligator_(film)' and (text() = 'Alligator' or . = 'Alligator')]</value>
      <webElementGuid>28647906-19a4-4f4f-8f0f-a8bcec303c2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
