<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HDB resale portal</name>
   <tag></tag>
   <elementGuidId>870701db-e1e7-41c8-95fe-fca3f13aa647</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'HDB resale portal')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ol > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cadd3d6f-dd65-4941-9327-31633090a7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://services2.hdb.gov.sg/webapp/BB31AWDashboardWeb/BB31PLogin.jsp</value>
      <webElementGuid>b16bde43-0ab4-4d9f-a069-b30488463fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>2ec19718-829d-46be-afe7-7f9d16af4ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>ecd8f2dd-8ca9-49f9-a89c-0211bf0c4036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HDB resale portal</value>
      <webElementGuid>45992ffc-8042-407a-bc51-b5c9c57312b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;post-template-default single single-post postid-21659 single-format-standard no-sidebar elementor-default elementor-template-canvas elementor-kit-6 elementor-page-24733 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-24733 elementor-location-single post-21659 post type-post status-publish format-standard has-post-thumbnail hentry category-hdb-blog category-resale-hdb category-en-sg tag-3-room tag-3gen tag-4-room tag-5-room tag-executive-apartment tag-featured tag-maisonette tag-mature-estate tag-non-mature-estate tag-property-agent tag-sell-hdb country-en-sg&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-4cc44b0e elementor-section-boxed elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-33fe56c5 ohmyhome-blog-wrapper-content-container-left&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-10df22e8 elementor-widget elementor-widget-theme-post-content&quot;]/div[@class=&quot;elementor-widget-container&quot;]/ol[1]/li[1]/a[1]</value>
      <webElementGuid>bce8a929-8e78-4cd9-8919-8bbfe13b08fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'HDB resale portal')]</value>
      <webElementGuid>cc1cb2c0-2817-4ad7-be70-48b9a277df2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://services2.hdb.gov.sg/webapp/BB31AWDashboardWeb/BB31PLogin.jsp')]</value>
      <webElementGuid>e181fe86-a43d-4852-8173-ddcd3264ceec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li/a</value>
      <webElementGuid>60c47526-0b16-47a3-9549-df991ac6a50e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://services2.hdb.gov.sg/webapp/BB31AWDashboardWeb/BB31PLogin.jsp' and (text() = 'HDB resale portal' or . = 'HDB resale portal')]</value>
      <webElementGuid>fe962eae-010a-4e98-9061-97637195513b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
