<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Elephant (1989 film)</name>
   <tag></tag>
   <elementGuidId>8fdf6619-28f0-4b46-b9f5-ac45a4e56aad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mw-content-ltr.mw-parser-output > ul > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7c6c18a5-1e81-401e-b31f-dd93e4a42e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Elephant_(1989_film)</value>
      <webElementGuid>57fce0e0-ba50-42fa-bec3-d27afe79abe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Elephant (1989 film)</value>
      <webElementGuid>bbf2fd5a-7449-4ed6-b967-2fd4e090c35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>07713f7f-10f6-4f92-8992-cfd269fa1749</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/ul/li/a</value>
      <webElementGuid>ac482f27-2568-4362-8200-ea140b3e4c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wiki/Elephant_(1989_film)')]</value>
      <webElementGuid>d66534c2-fc65-4f64-81b6-b265b1d0789a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/ul/li/a</value>
      <webElementGuid>09debb2b-2521-4beb-8058-9295b24f83e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Elephant_(1989_film)' and (text() = 'Elephant (1989 film)' or . = 'Elephant (1989 film)')]</value>
      <webElementGuid>1e650070-84c7-4dac-aa63-90498d5eef13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
