<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shrimp (disambiguation)</name>
   <tag></tag>
   <elementGuidId>21283f9e-1880-41d6-9c18-1b4a033daa6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mw-disambig</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dcd2eb52-acfb-40a6-826f-1adac248b43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Shrimp_(disambiguation)</value>
      <webElementGuid>240e59bf-3253-441f-96d9-7cf26d69a10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mw-disambig</value>
      <webElementGuid>5459173d-98a0-4fa3-b902-48dac46e24e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shrimp (disambiguation)</value>
      <webElementGuid>f79a7bdd-4532-4222-a0ec-c70ea264e40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/div[@class=&quot;hatnote navigation-not-searchable&quot;]/a[@class=&quot;mw-disambig&quot;]</value>
      <webElementGuid>57229b2f-fc5d-468a-8402-de3fc4fa14e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/div[2]/a</value>
      <webElementGuid>56e594ff-518d-481d-8035-ab7d9962590c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Shrimp (disambiguation)')]</value>
      <webElementGuid>870b94d7-7ec8-4bf8-895d-6659be212e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wiki/Shrimp_(disambiguation)')]</value>
      <webElementGuid>c212f739-6a99-4dc8-a56e-cbb10fd649e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div[2]/a</value>
      <webElementGuid>a64f9cdd-e56c-47e2-b22b-b8f74af49991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Shrimp_(disambiguation)' and (text() = 'Shrimp (disambiguation)' or . = 'Shrimp (disambiguation)')]</value>
      <webElementGuid>657d0049-8d92-4a22-8f29-c73afd250f7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
