<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Yes</name>
   <tag></tag>
   <elementGuidId>3196f95f-fb27-454f-ac7f-d618281d50ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e9d4093f-9710-45cd-bffb-5819d7c7b28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttontext2 inline-flex items-center justify-center gap-2 rounded-lg ring-offset-white transition-colors focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50 bg-ink-50 hover:bg-ink-100 text-ink-800 cursor-pointer max-h-[41px] px-4 py-3 md:max-h-[51px] md:py-4</value>
      <webElementGuid>c019764b-45c2-4922-98c1-bf8bb8047078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2f3b6bbf-d2ed-48e3-afde-976124fdb23f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ohmyhome.com/en-sg/property-valuation/</value>
      <webElementGuid>47b7178a-6439-4781-b3e1-b6b6d854fb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>85a5f329-aa3d-4c01-aa3b-99ed89e200d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:Rqqqmmmmlla:&quot;)/div[1]/div[@class=&quot;mt-6 flex flex-row justify-between border-t border-t-ink-100 pt-4&quot;]/a[@class=&quot;buttontext2 inline-flex items-center justify-center gap-2 rounded-lg ring-offset-white transition-colors focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50 bg-ink-50 hover:bg-ink-100 text-ink-800 cursor-pointer max-h-[41px] px-4 py-3 md:max-h-[51px] md:py-4&quot;]</value>
      <webElementGuid>a103e504-88b3-45c5-8250-95c93365fff7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@type='submit']</value>
      <webElementGuid>aab924aa-9b84-46e8-9800-c66e830d314c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:Rqqqmmmmlla:']/div/div[2]/a</value>
      <webElementGuid>10f230ce-9875-4021-88de-eca77dd4c918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ohmyhome.com/en-sg/property-valuation/')]</value>
      <webElementGuid>51be87af-190a-462b-af5e-dfcc95741af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>84e192e3-eaae-4654-bd96-091d8320bcbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'submit' and @href = 'https://ohmyhome.com/en-sg/property-valuation/' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>81f6ea12-4164-4325-aa7b-9df617c4a0c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
