<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_h-4 w-4</name>
   <tag></tag>
   <elementGuidId>6527c5d8-a19f-405c-9d2a-76cc70350b69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.h-4.w-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>6bbc4a98-d83e-4299-9398-8410c197afed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>99f84b1d-80d5-4c0b-b8b4-a5277bae2fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>cc3afbab-70fe-4de0-b3e2-6daca48a8170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>8330e914-332f-4476-b0a3-d55ce68bdf71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>1.5</value>
      <webElementGuid>0ce3de4b-305b-40c0-a6a2-0d6483dc5577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>aa7d1069-64ce-4220-8c8d-51543af70a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-4 w-4</value>
      <webElementGuid>6eb33069-0d83-43a1-9b6c-3473a5307b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;seller-onboard-contact-info&quot;)/button[@class=&quot;flex items-center justify-center transition-colors focus-visible:outline-none disabled:cursor-not-allowed rounded-full bg-light-900 text-ink-900 hover:bg-ink-50 border border-transparent overflow-hidden p-2 ml-4 h-8 w-8 md:ml-0&quot;]/svg[@class=&quot;h-4 w-4&quot;]</value>
      <webElementGuid>6df91695-ff31-43bb-954c-9f1bd23bd69b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
