<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Book an agent</name>
   <tag></tag>
   <elementGuidId>fa3cb939-0fd9-456f-b64f-9633e4a13a20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='en_sg_rent_tenant_agent_service_book_agent_banner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#en_sg_rent_tenant_agent_service_book_agent_banner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1beebfd7-12f0-435e-95bb-c35fe4b390c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-button elementor-button-link elementor-size-xs</value>
      <webElementGuid>df3c1b7c-fcd3-4a75-8d32-e5a1c131f001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ohmyhome.com/en-sg/property-agent-services/get-in-touch/</value>
      <webElementGuid>08b76fac-5ed9-4140-8e54-f9b48f2187b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>en_sg_rent_tenant_agent_service_book_agent_banner</value>
      <webElementGuid>8254fac8-f14a-4ac6-9a55-0e99666dfcf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Book an agent</value>
      <webElementGuid>dd442a34-6221-4e74-8abd-a04aa636f2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;en_sg_rent_tenant_agent_service_book_agent_banner&quot;)</value>
      <webElementGuid>d61bfe9d-a5ea-40b6-982d-1aa1aae1fbe9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='en_sg_rent_tenant_agent_service_book_agent_banner']</value>
      <webElementGuid>cb31a513-3091-4452-abb7-513541e45231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ohmyhome.com/en-sg/property-agent-services/get-in-touch/')]</value>
      <webElementGuid>3c5a2451-654a-454f-a396-5fb5b28bc42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a</value>
      <webElementGuid>17708a86-2a95-4fdb-be8d-4334253b2ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ohmyhome.com/en-sg/property-agent-services/get-in-touch/' and @id = 'en_sg_rent_tenant_agent_service_book_agent_banner' and (text() = 'Book an agent' or . = 'Book an agent')]</value>
      <webElementGuid>e3383fdd-02ea-45d8-90f9-751a80c1934f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
