<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_FishGill-bearing non-tetrapod aquatic ver_60fab8</name>
   <tag></tag>
   <elementGuidId>268e1a81-512e-4542-9228-ff1802627c6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='typeahead-suggestions']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.suggestion-link.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c9bfe427-5ff8-4d4b-a85a-49c8a2cdd61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>suggestion-link active</value>
      <webElementGuid>ef51fef8-7090-4f15-924f-9d046eb9c191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://en.wikipedia.org/wiki/Fish</value>
      <webElementGuid>f7456fa6-f2a7-4dab-923b-1959afbee906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FishGill-bearing non-tetrapod aquatic vertebrates</value>
      <webElementGuid>82ce1164-f35f-4754-af09-b4a712d42452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typeahead-suggestions&quot;)/div[@class=&quot;suggestions-dropdown&quot;]/a[@class=&quot;suggestion-link active&quot;]</value>
      <webElementGuid>66aa2a42-d7b5-45f8-946d-f7e30aa31a0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='typeahead-suggestions']/div/a</value>
      <webElementGuid>cc9b2dcc-e247-43db-92ab-a8ad39dc279c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://en.wikipedia.org/wiki/Fish')]</value>
      <webElementGuid>f2613b5e-0491-4b11-82b2-cbc2f225e211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>1052e219-9987-4488-86e2-915c6e1c039c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://en.wikipedia.org/wiki/Fish' and (text() = 'FishGill-bearing non-tetrapod aquatic vertebrates' or . = 'FishGill-bearing non-tetrapod aquatic vertebrates')]</value>
      <webElementGuid>5f213439-0a3e-4a56-8cea-d923e9c39878</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
