<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ShrimpDecapod crustaceans</name>
   <tag></tag>
   <elementGuidId>32e19ad4-c010-42b8-a71a-4be862aec6c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='typeahead-suggestions']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.suggestion-link.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2036ea48-c867-405a-af76-f67c130b649f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>suggestion-link active</value>
      <webElementGuid>4eac271e-825c-4475-b726-644757b1b13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://en.wikipedia.org/wiki/Shrimp</value>
      <webElementGuid>8813f7ef-1c9d-4c88-b709-30fa4e09c98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ShrimpDecapod crustaceans</value>
      <webElementGuid>8224ed99-831a-4c21-bad3-4c0864da03e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typeahead-suggestions&quot;)/div[@class=&quot;suggestions-dropdown&quot;]/a[@class=&quot;suggestion-link active&quot;]</value>
      <webElementGuid>b9cd1fe1-9cc9-4e52-aba2-027951a5d280</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='typeahead-suggestions']/div/a</value>
      <webElementGuid>3e90c67b-318f-4d57-bbe1-2c8bea30a91a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://en.wikipedia.org/wiki/Shrimp')]</value>
      <webElementGuid>d9fdc7bd-3776-4dec-a0ef-6f89c27b82ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>86110bee-1d20-49cc-83c0-0d93d673e527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://en.wikipedia.org/wiki/Shrimp' and (text() = 'ShrimpDecapod crustaceans' or . = 'ShrimpDecapod crustaceans')]</value>
      <webElementGuid>ca02a08e-e753-4b7b-a8b0-50ea2c9e447a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
