<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Giraffe</name>
   <tag></tag>
   <elementGuidId>e38bdc49-1ea7-410c-a7aa-e5758e0057f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='typeahead-suggestions']/div/a/div/h3/em</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>em.suggestion-highlight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>a36c8e58-93e5-4391-b575-ab353fd369f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>suggestion-highlight</value>
      <webElementGuid>64dc4892-75a1-4941-84d8-281112a51b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Giraffe</value>
      <webElementGuid>83a9f811-00eb-427a-af3e-30d8f6d86fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typeahead-suggestions&quot;)/div[@class=&quot;suggestions-dropdown&quot;]/a[@class=&quot;suggestion-link active&quot;]/div[@class=&quot;suggestion-text&quot;]/h3[@class=&quot;suggestion-title&quot;]/em[@class=&quot;suggestion-highlight&quot;]</value>
      <webElementGuid>70ed3333-d9ad-4520-9d56-272618c00c26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='typeahead-suggestions']/div/a/div/h3/em</value>
      <webElementGuid>30d2cc67-5592-42a0-88a2-aa7700f06f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//em</value>
      <webElementGuid>2eea1790-5258-427f-a8da-5c20660e3cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[(text() = 'Giraffe' or . = 'Giraffe')]</value>
      <webElementGuid>73ded877-5c4b-4d08-a389-d6a1e2e94d71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
