<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Horse</name>
   <tag></tag>
   <elementGuidId>3cb94598-e67f-4f0a-8cce-a2dcfa2097ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='typeahead-suggestions']/div/a/div/h3/em</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>em.suggestion-highlight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>cc5ecb8e-88d9-442d-8c85-a7eed88d6513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>suggestion-highlight</value>
      <webElementGuid>5a8a5aad-26cd-4e8e-8ee6-b3264f17bace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Horse</value>
      <webElementGuid>52a2d794-c3ad-4204-b685-4960d6fec9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typeahead-suggestions&quot;)/div[@class=&quot;suggestions-dropdown&quot;]/a[@class=&quot;suggestion-link active&quot;]/div[@class=&quot;suggestion-text&quot;]/h3[@class=&quot;suggestion-title&quot;]/em[@class=&quot;suggestion-highlight&quot;]</value>
      <webElementGuid>befe9cd1-0fe1-400c-8ec5-d8f11b2fc569</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='typeahead-suggestions']/div/a/div/h3/em</value>
      <webElementGuid>7577ed58-c866-4c64-9640-d2d4f6d19d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//em</value>
      <webElementGuid>91d5331f-2a9d-4c18-a73f-ccf6a1e67126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[(text() = 'Horse' or . = 'Horse')]</value>
      <webElementGuid>dede4fd3-e5a8-479d-9345-2faa4d84eabc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
