<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Orangutan</name>
   <tag></tag>
   <elementGuidId>08b717e9-7bf3-4872-8479-e5b56f67c869</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='typeahead-suggestions']/div/a/div/h3/em</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>em.suggestion-highlight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>2eb33943-4da5-4b4c-80e9-839c72e0ee1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>suggestion-highlight</value>
      <webElementGuid>244f2223-ae3e-4b74-8e9b-8f23bcb40019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Orangutan</value>
      <webElementGuid>3d3fad6c-2da6-4e3f-bc65-2db33cf220f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typeahead-suggestions&quot;)/div[@class=&quot;suggestions-dropdown&quot;]/a[@class=&quot;suggestion-link active&quot;]/div[@class=&quot;suggestion-text&quot;]/h3[@class=&quot;suggestion-title&quot;]/em[@class=&quot;suggestion-highlight&quot;]</value>
      <webElementGuid>69c9ab55-3dbe-451f-b553-a63e05c6a307</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='typeahead-suggestions']/div/a/div/h3/em</value>
      <webElementGuid>d5ed9d39-b54f-42a4-9be3-216eaa8f38f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//em</value>
      <webElementGuid>2dad257f-7e63-45d7-a4fa-aadd237f31d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[(text() = 'Orangutan' or . = 'Orangutan')]</value>
      <webElementGuid>c3d6e74a-173a-432f-be17-8bdd57e771aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
