<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Worm</name>
   <tag></tag>
   <elementGuidId>21d7628a-c20c-487f-9350-ecabc7e74487</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='typeahead-suggestions']/div/a/div/h3/em</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>em.suggestion-highlight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>427ef7ed-5c82-4ce5-a314-808645ddb4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>suggestion-highlight</value>
      <webElementGuid>935b46d9-1b6d-4dff-be54-44e012cee779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Worm</value>
      <webElementGuid>7ff98b10-0954-44e2-aace-330edd77fe94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typeahead-suggestions&quot;)/div[@class=&quot;suggestions-dropdown&quot;]/a[@class=&quot;suggestion-link active&quot;]/div[@class=&quot;suggestion-text&quot;]/h3[@class=&quot;suggestion-title&quot;]/em[@class=&quot;suggestion-highlight&quot;]</value>
      <webElementGuid>ad0670d0-87b5-4d13-a201-22fafb12b5f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='typeahead-suggestions']/div/a/div/h3/em</value>
      <webElementGuid>9293edcb-41d9-4c9f-a90e-9031c36c53f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//em</value>
      <webElementGuid>c93e9368-9ab7-4826-a212-b0e40b70bd94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[(text() = 'Worm' or . = 'Worm')]</value>
      <webElementGuid>4c85d692-7b79-4fcd-ab30-ca59454d75cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
