<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Earth</name>
   <tag></tag>
   <elementGuidId>0bacde8b-874f-4086-9a1e-a05f5c575fab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/p[11]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(11) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>00217fbf-d813-4a25-9b3d-556f9c5b0b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Earth</value>
      <webElementGuid>a10363b1-9f31-49db-8c2f-73dcdf3dd2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Earth</value>
      <webElementGuid>78032e3c-a6bc-4c1f-8a5b-a206b41246dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/p[11]/a[1]</value>
      <webElementGuid>c914bbef-37c0-479b-84de-f94d9e8d16f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/p[11]/a</value>
      <webElementGuid>ee929218-db76-40f6-9c65-a432903f65cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Earth')]</value>
      <webElementGuid>3c4e984d-dd28-423e-a120-2bbadeeeff05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wiki/Earth')]</value>
      <webElementGuid>bb22852b-eac2-405b-8287-dac4ff8bb69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[11]/a</value>
      <webElementGuid>a264667d-66be-40f7-a7a3-515b04e0796f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Earth' and (text() = 'Earth' or . = 'Earth')]</value>
      <webElementGuid>c3a0a9b7-2b3c-4285-a991-8cc63b452d6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
