<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_invertebrates</name>
   <tag></tag>
   <elementGuidId>74bad0a8-072a-4b5b-b279-53c983801dba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/p[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(2) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c65a4dcb-9432-4973-9ab4-b90b0e1efa99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Invertebrate</value>
      <webElementGuid>3af73bf9-afe0-405b-97e0-5018c694f10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>invertebrates</value>
      <webElementGuid>db9b6c17-c43c-4d8c-b8e1-81bc62b2bb27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/p[2]/a[1]</value>
      <webElementGuid>bcd6d750-4cfd-4d98-8d57-2df42b4e2d77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/p[2]/a</value>
      <webElementGuid>48915e01-2c48-4380-a946-5472c9ff8676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'invertebrates')]</value>
      <webElementGuid>797abdc4-4ceb-4518-bf7b-7555f61210b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wiki/Invertebrate')]</value>
      <webElementGuid>1dbae91a-3e0b-431f-ad6b-2aefa858d873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
      <webElementGuid>b973bb8b-59fb-4736-ae04-4adab129e7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Invertebrate' and (text() = 'invertebrates' or . = 'invertebrates')]</value>
      <webElementGuid>c44a28bf-80c2-4962-a514-5923f9b4bd1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
