<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All Countries                       _716932</name>
   <tag></tag>
   <elementGuidId>b0c3fca9-44ed-4e90-ba71-cf3a1187b5f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='countries']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#countries</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3bfec183-cd75-455d-b95a-e47d9e3faee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>countries</value>
      <webElementGuid>82274546-1542-493a-bf65-6c3be7e8c2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>countries</value>
      <webElementGuid>cc069a0f-b53d-49c6-b5a7-f7fd0608b5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            All Countries
                                                            Philippines
                                                            Singapore
                                                            Malaysia
                                                    </value>
      <webElementGuid>7884a1f1-870b-453b-86da-d38a4374f7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;countries&quot;)</value>
      <webElementGuid>328696a5-2baf-46f5-bad7-00573b55cb0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='countries']</value>
      <webElementGuid>be2e4061-00ba-43a0-afb4-0e5a88e538d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='job-list']/div/div[3]/select</value>
      <webElementGuid>3f89b0c3-a569-40b7-bb69-7fad2ba84a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>54222a52-839a-4267-9f72-7a31f14b984a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'countries' and @id = 'countries' and (text() = '
                            All Countries
                                                            Philippines
                                                            Singapore
                                                            Malaysia
                                                    ' or . = '
                            All Countries
                                                            Philippines
                                                            Singapore
                                                            Malaysia
                                                    ')]</value>
      <webElementGuid>80ee05dd-4c0d-4c94-8373-36e52b9e75e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
