<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>c31ea832-1411-47e0-8637-916399f0b9ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>76dc76cf-cd12-4b72-a852-8aeaca09e407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>132</value>
      <webElementGuid>366b0564-da5d-43bf-a195-83c3f73b814e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>0fbc9690-6398-4ebb-950c-e05cf37f92ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 132 24</value>
      <webElementGuid>6a5b0224-7593-44d4-80c0-c20b03e8f223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>8558e19d-edf9-4695-af06-836507b078b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>29ef6e4f-054a-44b8-8a98-29f83c2283fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;post-template-default single single-post postid-76892 single-format-standard no-sidebar elementor-default elementor-template-canvas elementor-kit-6 elementor-page-24733 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-24733 elementor-location-single post-76892 post type-post status-publish format-standard has-post-thumbnail hentry category-hdb-blog category-resale-hdb category-en-sg tag-featured tag-hdb-resale tag-hdb-resale-market tag-sell-hdb country-en-sg&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-914f180 elementor-section-full_width hide-during-webview elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-13e124d&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-7ce79bf elementor-widget elementor-widget-header-menu&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;ohmyhome-mega-menu-header-wrapper&quot;]/header[1]/div[@class=&quot;ohmyhome-mega-menu-header-container-wrapper&quot;]/div[@class=&quot;singapore-desktop-mega-menu ohmyhome-mega-menu-header-container&quot;]/div[@class=&quot;desktop-mega-menu-left-col&quot;]/div[@class=&quot;logo-container&quot;]/div[@class=&quot;logo-country-wrapper&quot;]/a[1]/svg[1]</value>
      <webElementGuid>bafbbae2-57d1-4b5c-926f-47373f7a74e8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
