<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_sexual reproduction</name>
   <tag></tag>
   <elementGuidId>4e3f5374-6e71-44b7-a76d-90ac0464bd0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/p[2]/a[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(7)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4cd60192-a804-4e87-8d50-be1ba4e42dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Sexual_reproduction</value>
      <webElementGuid>d119e8de-781f-43f8-a296-c21a6ee6e1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sexual reproduction</value>
      <webElementGuid>35fd506a-40d6-4579-81e2-e10750e1e2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/p[2]/a[7]</value>
      <webElementGuid>5d4cf2f9-8f57-49f6-85e3-21fc1bc8ca05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/p[2]/a[7]</value>
      <webElementGuid>114f875c-e92b-4805-8394-2f95a46104f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'sexual reproduction')]</value>
      <webElementGuid>995af4b0-dde8-4360-9731-e1c7eb0a3792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wiki/Sexual_reproduction')]</value>
      <webElementGuid>2f69d6d8-19b7-4d5c-903e-9f73712af16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[7]</value>
      <webElementGuid>afb5d900-b00b-46e3-8d7d-d4d621651dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Sexual_reproduction' and (text() = 'sexual reproduction' or . = 'sexual reproduction')]</value>
      <webElementGuid>dd34a37d-2b52-41a8-b5e7-33d184a8583c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
