<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_terrestrial</name>
   <tag></tag>
   <elementGuidId>e5c57511-59a3-4ae3-bb0c-78ff8f7e0aae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/p[2]/a[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mw-redirect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b67a5e86-95c4-4e1e-9210-5de818dfc3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Terrestrial_ecoregion</value>
      <webElementGuid>c57308fd-5855-4a0f-a12e-751534ea5938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mw-redirect</value>
      <webElementGuid>cf4e7f1c-8e0e-4754-9b24-b1d806eac5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>terrestrial</value>
      <webElementGuid>bb8b271c-f9fb-4c9b-8d8b-095eb97d4914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/p[2]/a[@class=&quot;mw-redirect&quot;]</value>
      <webElementGuid>abc469fa-8af9-495b-8839-9873a8a577f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/p[2]/a[11]</value>
      <webElementGuid>dc6ef890-1298-46be-a145-03cdcc0f3efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'terrestrial')]</value>
      <webElementGuid>0273d95f-7a19-4f7b-af98-e26ab86204af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wiki/Terrestrial_ecoregion')]</value>
      <webElementGuid>a282ebc1-5834-44b2-a2fb-473ba448bc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[11]</value>
      <webElementGuid>59ec4b24-df6c-42b4-a966-9fd3aad45c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Terrestrial_ecoregion' and (text() = 'terrestrial' or . = 'terrestrial')]</value>
      <webElementGuid>f53c5276-95fd-4576-ae6b-7e5d1a59c728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
