<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ytp-play-button ytp-button</name>
   <tag></tag>
   <elementGuidId>cea1475d-6b86-4b08-864e-3eec3f87a814</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='movie_player']/div[30]/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ytp-play-button.ytp-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb0422ee-e749-4841-8d2c-06ae7629e9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ytp-play-button ytp-button</value>
      <webElementGuid>c698c056-1285-4886-8516-850181c25653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-keyshortcuts</name>
      <type>Main</type>
      <value>k</value>
      <webElementGuid>957a6d17-bb0f-471a-bcae-3aae69712633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title-no-tooltip</name>
      <type>Main</type>
      <value>Pause</value>
      <webElementGuid>1670b5c1-6153-455b-8f11-3e25f9757f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Pause keyboard shortcut k</value>
      <webElementGuid>94142d43-dfc5-4080-a3fe-51545f76ca34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;movie_player&quot;)/div[@class=&quot;ytp-chrome-bottom&quot;]/div[@class=&quot;ytp-chrome-controls&quot;]/div[@class=&quot;ytp-left-controls&quot;]/button[@class=&quot;ytp-play-button ytp-button&quot;]</value>
      <webElementGuid>dc383061-d353-430e-b33d-4c075aef8029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Homer AI - Discover Your Home Valuatio_b4daff/iframewidget2</value>
      <webElementGuid>70e6c8a3-0bd3-466d-ac0c-337d2fe7d6b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='movie_player']/div[30]/div[2]/div/button</value>
      <webElementGuid>6a7ae488-b5d6-4b1f-9f83-610bf26f6f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>f0ccdd7b-5b10-486b-944b-0c33a1d10728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
