<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Whats coming next in Homer AI</name>
   <tag></tag>
   <elementGuidId>a7d15e61-4ddb-4255-ac5f-ac2a6596b11b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-1955']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-1955</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a2f4a57b-d63a-4b60-9808-75196f69dc99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>elementor-tab-title-1955</value>
      <webElementGuid>bc0ff3b4-30e3-4cdc-8c33-ad7e3d79ff60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-tab-title</value>
      <webElementGuid>5908f8f8-7e45-46ee-a76c-c8a2f976048c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>db374b17-6bd4-4992-82ce-d2f77ac4a8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00642020-9165-4ec8-aa15-f0c9a1acce60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>elementor-tab-content-1955</value>
      <webElementGuid>7a8aa223-325a-4b48-8569-b17649b470b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4941e88e-097d-4c22-b3d7-61bdb7f1ca25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>What’s coming next in Homer AI? </value>
      <webElementGuid>7180eee8-6d76-47e6-bdf6-6059390941b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-1955&quot;)</value>
      <webElementGuid>f9ec1e01-a887-4104-88a5-a454f7d23d86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-1955']</value>
      <webElementGuid>db124d1b-2d25-4e5e-927b-46e68125cd6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[8]/div/div[2]/div/div/div/div/div[5]/div</value>
      <webElementGuid>d04dc018-3472-42d6-af6f-23009529da4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'elementor-tab-title-1955' and (text() = 'What’s coming next in Homer AI? ' or . = 'What’s coming next in Homer AI? ')]</value>
      <webElementGuid>f60be27c-60e9-401d-a2d9-0814a1453975</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
