<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_What are the property types Homer AI supports</name>
   <tag></tag>
   <elementGuidId>c2cde3d8-e7b6-477d-aff0-9ba7708a0a02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-1953']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-1953</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b37d1476-d509-42fc-952d-7e9ccc11ed29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>elementor-tab-title-1953</value>
      <webElementGuid>5ccede1c-6f38-4a9c-a1d9-e3b2c0e7d3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-tab-title</value>
      <webElementGuid>5fcdc6a8-09de-4bd4-a497-f7357edfbd5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f3b82f9e-ae2d-4041-9e4b-10a41ed5de6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1e85b835-00a8-4967-ba9c-9fbe84af0406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>elementor-tab-content-1953</value>
      <webElementGuid>5cbf7d89-31b1-49ab-8460-96ea888247be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>85beba0f-b6dd-4efa-ac9e-a7f76944948e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>What are the property types Homer AI supports?</value>
      <webElementGuid>02327a57-cbcf-4532-8c7e-ae97cdcf29aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-1953&quot;)</value>
      <webElementGuid>257ce5b4-876f-43c5-ae31-77d4333c1eea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-1953']</value>
      <webElementGuid>ec62d268-cc5c-4537-82d5-d18d8fa26e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[8]/div/div[2]/div/div/div/div/div[3]/div</value>
      <webElementGuid>32b61f6f-af16-45b9-8d9c-a26ba5b655c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'elementor-tab-title-1953' and (text() = 'What are the property types Homer AI supports?' or . = 'What are the property types Homer AI supports?')]</value>
      <webElementGuid>66ba8884-a097-4ed4-93c1-783867249a9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
