<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_What is Homer AI</name>
   <tag></tag>
   <elementGuidId>bdb66d60-9b9e-4d2a-9bd1-9b7953ca4c55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-1951']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-1951</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>53c5d12b-32c4-4498-b084-c5fbfdd338b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>elementor-tab-title-1951</value>
      <webElementGuid>26b3c1ca-705e-48cd-b833-fbe30212c481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-tab-title</value>
      <webElementGuid>cb6af4d6-cd35-4ca5-8e60-7faaf8475164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8e9daa4c-9cc8-4587-8441-808094ee5454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b7b9a499-bd25-44fc-86f9-5e9b46cd2371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>elementor-tab-content-1951</value>
      <webElementGuid>c373077e-5fac-4cc0-82e4-4edca63ca423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e634d81a-a050-41ca-841c-9d62edb1c970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>What is Homer AI?</value>
      <webElementGuid>90a7443e-1ecb-49bb-b38d-ba898cb71e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-1951&quot;)</value>
      <webElementGuid>0a04bfd0-d2b8-477f-8c51-669941bf8736</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-1951']</value>
      <webElementGuid>57fa26ff-1b20-41ff-9b9d-0096e0a914e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[8]/div/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>34648f79-17a0-4fc1-b4c8-ed57bb87e017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'elementor-tab-title-1951' and (text() = 'What is Homer AI?' or . = 'What is Homer AI?')]</value>
      <webElementGuid>0c8706e8-9d20-491b-9f04-543d48d9f4cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
