<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Why should I trust Homer AIs e-Valuation</name>
   <tag></tag>
   <elementGuidId>b88c92be-873d-4ad7-8be4-df769d089610</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-1952']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-1952</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>73bdd8fe-b2bd-4e39-8e18-0b6d8cdfef9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>elementor-tab-title-1952</value>
      <webElementGuid>362507bb-bbac-4707-8cf5-40053e4b96fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-tab-title</value>
      <webElementGuid>be601948-2bc9-4dcd-80f3-a835add1c9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>fde3b04c-2371-4df7-a551-77295ccbe662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d89d67af-62bc-452f-8d17-d1bd003d7f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>elementor-tab-content-1952</value>
      <webElementGuid>5dc0cc5b-9b99-4f0a-bb9d-00fd8c99adf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>17a1e0d6-249c-40bb-a1c5-a9da59e1a597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Why should I trust Homer AI’s e-Valuation?</value>
      <webElementGuid>11ad5c9d-973a-4918-824f-10410fa7f185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-1952&quot;)</value>
      <webElementGuid>1d51228e-b5ef-445f-832c-5f2c490d077d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-1952']</value>
      <webElementGuid>f2a2fe4d-2a79-4055-9623-6adeb0d172b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[8]/div/div[2]/div/div/div/div/div[2]/div</value>
      <webElementGuid>f4dde636-e260-438e-a576-c9f209b4b697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'elementor-tab-title-1952' and (text() = 'Why should I trust Homer AI’s e-Valuation?' or . = 'Why should I trust Homer AI’s e-Valuation?')]</value>
      <webElementGuid>8a345a58-622d-48bb-b4e2-5e51ca6659f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
