<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_How Homer AI helps me to manage my property</name>
   <tag></tag>
   <elementGuidId>ec9c3cd2-a94c-4090-9ead-0bf820eb3b5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-1954']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-1954</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3b59aa8d-5108-4351-a208-0e941a385e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>elementor-tab-title-1954</value>
      <webElementGuid>2047d681-f7a6-4cf5-9731-fb79bebd898a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-tab-title</value>
      <webElementGuid>531a2678-2248-4112-93be-f469537e59b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>1e172d99-9399-4e2d-81fb-f719a607481e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1077f6c7-e9a7-406a-b797-b8c45259b684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>elementor-tab-content-1954</value>
      <webElementGuid>eaf1e003-63e8-45ba-bc2f-34b08bb3c361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>828cc35e-f701-411f-859b-61c79a95c095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>How Homer AI helps me to manage my property?</value>
      <webElementGuid>d7db0fbe-2b4f-418a-9275-9b53d4129b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-1954&quot;)</value>
      <webElementGuid>f697e144-8d49-4734-8df7-43a841a5d305</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-1954']</value>
      <webElementGuid>0d514e3e-66fa-4042-ae0c-743801dedd7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[8]/div/div[2]/div/div/div/div/div[4]/div</value>
      <webElementGuid>0259226e-a0eb-4249-93b2-c0ae7ce71cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'elementor-tab-title-1954' and (text() = 'How Homer AI helps me to manage my property?' or . = 'How Homer AI helps me to manage my property?')]</value>
      <webElementGuid>72ff9945-cca3-442a-804b-d0df5a410970</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
