<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ecosystem</name>
   <tag></tag>
   <elementGuidId>bba60c08-2580-4f8a-85ec-ab0c9f342c54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/p[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(2) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ad1f346e-9873-4623-993c-f1334defb9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Ecosystem</value>
      <webElementGuid>1d577eeb-4258-4bed-acc4-c99f4f82241c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ecosystem</value>
      <webElementGuid>c60cba66-9199-4dc5-a0f0-2807605a2c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/p[2]/a[1]</value>
      <webElementGuid>d9541e50-1fdd-4453-84e0-b438766ea8df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/p[2]/a</value>
      <webElementGuid>90906056-0992-415d-8775-5b6a9e6dd0e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ecosystem')]</value>
      <webElementGuid>e586edbb-5f8d-4068-bbf0-f6fc49a6ae52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wiki/Ecosystem')]</value>
      <webElementGuid>ac612aa7-8ea3-4223-b3d3-6e95db1ff373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
      <webElementGuid>80c5c2eb-0997-44d6-acf6-2a97169e3895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Ecosystem' and (text() = 'ecosystem' or . = 'ecosystem')]</value>
      <webElementGuid>c9141b4b-26b2-4933-8fc1-b67876cd38fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
