<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Blog</name>
   <tag></tag>
   <elementGuidId>19470b17-7701-44d7-809e-c51a17b46e9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Blog')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>03892924-6126-47a2-a713-11164bcb63eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en-ph/blog/</value>
      <webElementGuid>a092ec55-565f-4215-9a5e-cff2da7c2a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>omh-footer-menu-tracking</value>
      <webElementGuid>879c4e2d-d096-4e31-aa3b-3496af5e7239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text</name>
      <type>Main</type>
      <value>Blog</value>
      <webElementGuid>0a7f489a-9d0a-42cb-b642-54566006d9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blog </value>
      <webElementGuid>be8ec374-9efc-4c28-b39f-cc9890d87e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-7046 page-parent no-sidebar elementor-default elementor-template-canvas elementor-kit-6 elementor-page elementor-page-7046 elementor-page-51482 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-51482 elementor-location-single post-7046 page type-page status-publish hentry country-en-ph&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-3abfbd5 elementor-section-full_width hide-during-webview elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-9a12298&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-1b52a17 elementor-widget elementor-widget-footer&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;footer-wrapper&quot;]/div[@class=&quot;footer-container&quot;]/div[@class=&quot;footer-middle-col&quot;]/div[@class=&quot;footer-menu-wrapper&quot;]/div[@class=&quot;footer-menu-block&quot;]/div[@class=&quot;footer-menu-item-container&quot;]/div[@class=&quot;footer-menu-item&quot;]/a[@class=&quot;omh-footer-menu-tracking&quot;]</value>
      <webElementGuid>d1e81c60-765f-419a-9c8f-243f46b76d12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Blog')]</value>
      <webElementGuid>03d540dc-8a74-4843-9e53-3a3c288bdc0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/en-ph/blog/')])[55]</value>
      <webElementGuid>850ef1d8-207b-4e34-ab06-2e10a5165a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/a</value>
      <webElementGuid>fba1d204-cbc1-4a12-a643-21741278f90d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en-ph/blog/' and (text() = ' Blog ' or . = ' Blog ')]</value>
      <webElementGuid>33543833-089c-491d-8a62-7dbefe664b4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
