<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Investors</name>
   <tag></tag>
   <elementGuidId>c14f465f-609d-4c7e-83ca-84c229be3adf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Investors')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ae788698-ba52-461d-9ec6-ad5836a31677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ir.ohmyhome.com</value>
      <webElementGuid>65243900-dc13-4c57-8acd-f4bd9e4b9c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>omh-footer-menu-tracking</value>
      <webElementGuid>3373b4f9-83eb-499a-ab66-229a1966ab27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text</name>
      <type>Main</type>
      <value>Investors</value>
      <webElementGuid>ca62d71a-deed-4f1b-a613-f0af1ccb0d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Investors </value>
      <webElementGuid>c839700a-a0a1-4e6f-b103-d1b6e8397fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-7046 page-parent no-sidebar elementor-default elementor-template-canvas elementor-kit-6 elementor-page elementor-page-7046 elementor-page-51482 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-51482 elementor-location-single post-7046 page type-page status-publish hentry country-en-ph&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-3abfbd5 elementor-section-full_width hide-during-webview elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-9a12298&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-1b52a17 elementor-widget elementor-widget-footer&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;footer-wrapper&quot;]/div[@class=&quot;footer-container&quot;]/div[@class=&quot;footer-middle-col&quot;]/div[@class=&quot;footer-menu-wrapper&quot;]/div[@class=&quot;footer-menu-block&quot;]/div[@class=&quot;footer-menu-item-container&quot;]/div[@class=&quot;footer-menu-item&quot;]/a[@class=&quot;omh-footer-menu-tracking&quot;]</value>
      <webElementGuid>d6d60f77-6e39-4496-b313-cf367c56e280</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Investors')]</value>
      <webElementGuid>86ed408d-227e-40c5-a645-9e9da206c06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ir.ohmyhome.com')]</value>
      <webElementGuid>b4238537-7f59-4cf3-abf5-f8b9c645dfa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]/a</value>
      <webElementGuid>06213f08-5c26-4199-943e-1fe81a8ab9e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ir.ohmyhome.com' and (text() = ' Investors ' or . = ' Investors ')]</value>
      <webElementGuid>b5e213c1-d3d9-47b3-8398-61187eafdfeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
