<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_How can I buy property if Im an OFW abroad</name>
   <tag></tag>
   <elementGuidId>a173d68c-e9f2-428c-9eb2-bef06a812cd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-7182']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-7182</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>94ab962a-e85b-434f-bf8f-3ecdb4d51c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>elementor-tab-title-7182</value>
      <webElementGuid>a9e70988-aec1-48f4-9aa8-5638e3c81ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-tab-title</value>
      <webElementGuid>a63184f6-f729-4e1f-a952-57a6d6b88f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>776eb28c-3662-42ac-8a4b-733f6b685d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>896792b9-f4b9-4e0c-8968-d249ec140f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>elementor-tab-content-7182</value>
      <webElementGuid>6d7ec96b-3d6a-4443-b29c-0cfdfc0a40bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>411dddc6-2031-4f07-9196-d8cec2393de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>How can I buy property if I'm an OFW abroad?</value>
      <webElementGuid>839965b5-b67a-4b2f-b7fb-f1bdf336019b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-7182&quot;)</value>
      <webElementGuid>f037a4c9-5617-449e-a61d-ebc376ceaf08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-7182']</value>
      <webElementGuid>08ef8233-ccd9-4cb7-b46b-3d933fb6e190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[14]/div/div[2]/div/div/div/div/div[2]/div</value>
      <webElementGuid>fb51f677-fd2d-49be-8443-8b7f3d7355be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'elementor-tab-title-7182' and (text() = concat(&quot;How can I buy property if I&quot; , &quot;'&quot; , &quot;m an OFW abroad?&quot;) or . = concat(&quot;How can I buy property if I&quot; , &quot;'&quot; , &quot;m an OFW abroad?&quot;))]</value>
      <webElementGuid>1ee1693b-3550-4765-8cdf-cf78bbf85fdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
