<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Are Ohmyhome agents accredited</name>
   <tag></tag>
   <elementGuidId>10a222ec-16a0-4999-9e64-df8fdfaa5eb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-7183']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-7183</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>234326a1-82c8-4421-b0fd-e028bd3fef47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>elementor-tab-title-7183</value>
      <webElementGuid>2b5cfb43-edc4-4878-bd6d-faff3e91b042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-tab-title</value>
      <webElementGuid>1e53053b-d3de-45c6-b3a4-b05a02832b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>95d05628-53f4-42b2-a2ad-0e74102f764a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c5881742-09b6-4b89-b5c7-663f4a1112fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>elementor-tab-content-7183</value>
      <webElementGuid>1374434f-9676-4b1c-adb3-6d342f625ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4cd3a49d-231e-44a0-a19e-faeca085e789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Are Ohmyhome agents accredited?</value>
      <webElementGuid>1a92752c-b91c-48b4-9be2-6c8f7733a7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-7183&quot;)</value>
      <webElementGuid>4f73453b-abc1-4377-8fda-0989650c7bc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-7183']</value>
      <webElementGuid>5c08d963-b127-4c73-9339-ca60d28d099b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[14]/div/div[2]/div/div/div/div/div[3]/div</value>
      <webElementGuid>b3668a64-8d91-45df-8372-ce90e8a80204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'elementor-tab-title-7183' and (text() = 'Are Ohmyhome agents accredited?' or . = 'Are Ohmyhome agents accredited?')]</value>
      <webElementGuid>ab8197ad-647e-4b0c-a81f-84684af2490a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
