<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Why should I invest in the Philippines</name>
   <tag></tag>
   <elementGuidId>f0f87219-4b29-4391-89bb-1b86435a7e2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-7184']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-7184</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bbbaba74-e7fa-4989-b15d-b71dbfbef783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>elementor-tab-title-7184</value>
      <webElementGuid>6c600626-c599-4197-9b29-2f20c7134508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-tab-title</value>
      <webElementGuid>0136127d-1fd6-40bb-8c12-6e1cffb321c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>22436572-d05a-438a-93c8-9f764aa29059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8afb6433-5444-49b4-a26b-459df73a9254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>elementor-tab-content-7184</value>
      <webElementGuid>f59b163b-8cc4-42f3-bbf6-b6c7b36825ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8b878f8b-35a6-4a41-8595-bbd4ef553cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Why should I invest in the Philippines?</value>
      <webElementGuid>07c32b48-cb95-439c-b379-a6b8a85f5312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-7184&quot;)</value>
      <webElementGuid>ac748195-709d-4c4e-a585-e1e7c2e37eb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-7184']</value>
      <webElementGuid>1ef89f5f-4adc-4511-82eb-688473a68c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[14]/div/div[2]/div/div/div/div/div[4]/div</value>
      <webElementGuid>05c4b415-6989-416d-9f08-24ffa0af5b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'elementor-tab-title-7184' and (text() = 'Why should I invest in the Philippines?' or . = 'Why should I invest in the Philippines?')]</value>
      <webElementGuid>1088c4af-1eda-478c-af2c-3ff828def479</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
