<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Why choose Ohmyhome</name>
   <tag></tag>
   <elementGuidId>9b3497ba-c7af-4a61-aabe-40fa26bbadf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-tab-title-7185']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#elementor-tab-title-7185</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b6a3ebbf-d86d-4f92-a5af-b055a679d370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>elementor-tab-title-7185</value>
      <webElementGuid>8c09fad4-52d4-4cb5-96ce-c631a54d0430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-tab-title</value>
      <webElementGuid>70a94c54-d691-4502-96a7-683fbfbd0a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>648e8048-939e-4ca5-b0d7-d5010ec2a0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>51be70ae-2026-4598-8b1c-366a52adfd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>elementor-tab-content-7185</value>
      <webElementGuid>6d49a1bc-c8f5-4112-8dfd-03c5598ca3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d9aeff08-5827-4ced-8532-629ff661656c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Why choose Ohmyhome?</value>
      <webElementGuid>489af923-ad2f-468d-9afd-42be1b3c5e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-tab-title-7185&quot;)</value>
      <webElementGuid>b461d525-3f21-46a4-9b45-9890fe9c3251</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='elementor-tab-title-7185']</value>
      <webElementGuid>999897e8-ff29-44a0-94a9-e64524ad5031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[14]/div/div[2]/div/div/div/div/div[5]/div</value>
      <webElementGuid>089d3903-1dc4-489f-8c15-aeb15af5569c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'elementor-tab-title-7185' and (text() = 'Why choose Ohmyhome?' or . = 'Why choose Ohmyhome?')]</value>
      <webElementGuid>e02350a7-d21d-4ddb-9304-4d39692ec2b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
