<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Zebra (disambiguation)</name>
   <tag></tag>
   <elementGuidId>85cd1269-4e56-4f8f-803c-1fe16a60710d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mw-disambig</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e001152a-68b4-4f1b-a36f-15528b252c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Zebra_(disambiguation)</value>
      <webElementGuid>5d48c6ac-cd9f-44ac-9e26-fdb324b28df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mw-disambig</value>
      <webElementGuid>59034c6f-02e8-45e6-88e4-2a09ec2e9b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Zebra (disambiguation)</value>
      <webElementGuid>98b469de-86d2-4da7-befb-08ca2a39c073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/div[@class=&quot;hatnote navigation-not-searchable&quot;]/a[@class=&quot;mw-disambig&quot;]</value>
      <webElementGuid>a5503b1e-b903-421c-aa1a-fd82e532fab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/div[2]/a</value>
      <webElementGuid>90a0d5a2-071f-4dee-9dae-ac284ee4b8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Zebra (disambiguation)')]</value>
      <webElementGuid>0a5b6415-1fa8-44ad-b60b-fd248a54e5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wiki/Zebra_(disambiguation)')]</value>
      <webElementGuid>7408eb9e-c9ae-48dd-aadb-a1e3d6b824eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div[2]/a</value>
      <webElementGuid>bd8c2510-6b19-47d4-92b3-6ae45e11a23c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Zebra_(disambiguation)' and (text() = 'Zebra (disambiguation)' or . = 'Zebra (disambiguation)')]</value>
      <webElementGuid>b2d24140-66c5-4fc4-9370-db3f2975e04a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
