<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Chondrichthyes</name>
   <tag></tag>
   <elementGuidId>00f0265a-554d-4011-9d8a-62bc36dcc53b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/p[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(2) > a:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>290c5187-2bd3-4caa-a5f8-ca8f6832f8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Chondrichthyes</value>
      <webElementGuid>dc4196e3-d152-4afa-a06e-1a02aad2dc0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chondrichthyes</value>
      <webElementGuid>6743ade7-4361-4f37-a8bf-5bfdcaa93810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/p[2]/a[2]</value>
      <webElementGuid>da4f6270-2fac-47bd-ab28-a157833e0321</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/p[2]/a[2]</value>
      <webElementGuid>53a0d4a0-f16d-44ac-aab5-a1cd194f1823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Chondrichthyes')])[2]</value>
      <webElementGuid>9ab7beb8-ef8c-4282-ad7a-8735574af923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/wiki/Chondrichthyes')])[2]</value>
      <webElementGuid>8f82f3ec-8407-4316-811e-266c4186aba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a[2]</value>
      <webElementGuid>8b6cbe3b-04e2-4372-8780-2fc5c2907332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Chondrichthyes' and (text() = 'Chondrichthyes' or . = 'Chondrichthyes')]</value>
      <webElementGuid>0dbf1b56-b16c-48f9-ac47-c0996567dfaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
