<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_65 9755 9283</name>
   <tag></tag>
   <elementGuidId>3547dcb1-9aab-450a-969b-351e4cbd83aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='en_sg_agent_whatsapp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#en_sg_agent_whatsapp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>136f9591-e1cb-4a83-b02f-4143a9ebf956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-button elementor-button-link elementor-size-xl</value>
      <webElementGuid>7aea061b-197e-4885-a19c-51e1967a3355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://api.whatsapp.com/send?phone=6597559283&amp;text=Hi%20Ohmyhome,%20I%20would%20like%20to%20enquire%20about%20your%20services.&amp;</value>
      <webElementGuid>e8b0ca01-7eda-4244-a7dd-5ddbddc1fb64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>5df469b1-eff2-4ce2-a1e9-14a639e83c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>en_sg_agent_whatsapp</value>
      <webElementGuid>0a30cc98-a464-4aa6-8f8b-5f0797101512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+65 9755 9283</value>
      <webElementGuid>8ed59f47-d29e-47cc-bfd2-33d11fe32f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;en_sg_agent_whatsapp&quot;)</value>
      <webElementGuid>4a36d386-5a26-4c42-a1b9-282c095b84a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='en_sg_agent_whatsapp']</value>
      <webElementGuid>520fe31f-5637-4279-b576-dc2a07f271a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://api.whatsapp.com/send?phone=6597559283&amp;text=Hi%20Ohmyhome,%20I%20would%20like%20to%20enquire%20about%20your%20services.&amp;')])[4]</value>
      <webElementGuid>fb4b777a-55ed-48e6-8562-9d44248c7233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]/div/div[3]/div/div/a</value>
      <webElementGuid>efc5abed-228c-4a09-afcc-d402a423b368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://api.whatsapp.com/send?phone=6597559283&amp;text=Hi%20Ohmyhome,%20I%20would%20like%20to%20enquire%20about%20your%20services.&amp;' and @id = 'en_sg_agent_whatsapp' and (text() = '+65 9755 9283' or . = '+65 9755 9283')]</value>
      <webElementGuid>b0aecb24-7a8a-49c4-98d5-1a6bebeba176</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
