<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_attachment-full size-full wp-image-1181_d0ac4d</name>
   <tag></tag>
   <elementGuidId>38142185-91b4-4d08-9957-984f4b1b40a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://ohmyhome.com/wp-content/uploads/2021/07/Image-4-2.png')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-full.size-full.wp-image-11812.entered.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>19dcfc08-d177-4815-9947-9d3eb6cc4cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>b3c7367b-d955-4355-844b-9dd5113c2d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>97bbad7f-7ac3-4184-b79d-b684d704fe9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>568</value>
      <webElementGuid>61eb5c2a-92b6-41e0-91cf-48f39703f209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>380</value>
      <webElementGuid>5f51b0a7-48dd-45bf-89af-5baacd476118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ohmyhome.com/wp-content/uploads/2021/07/Image-4-2.png</value>
      <webElementGuid>fcd8308b-9480-4aef-8c54-fca11150c7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-full size-full wp-image-11812 entered lazyloaded</value>
      <webElementGuid>8afca577-1f47-4853-9f6e-30c973f48a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-srcset</name>
      <type>Main</type>
      <value>https://ohmyhome.com/wp-content/uploads/2021/07/Image-4-2.png 568w, https://ohmyhome.com/wp-content/uploads/2021/07/Image-4-2-300x201.png 300w</value>
      <webElementGuid>e64ce267-e4b3-46f0-bd30-5aa439b5569f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-sizes</name>
      <type>Main</type>
      <value>(max-width: 568px) 100vw, 568px</value>
      <webElementGuid>16c8f245-9f7a-4d3f-bf49-2f47dc8bfb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://ohmyhome.com/wp-content/uploads/2021/07/Image-4-2.png</value>
      <webElementGuid>e0964eac-0109-47a2-ad8d-123c12e0dceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>5c3aff1d-0df0-48eb-8cf6-91179ac55406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 568px) 100vw, 568px</value>
      <webElementGuid>1f82c656-76ff-452e-8fd4-75e66c9180d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://ohmyhome.com/wp-content/uploads/2021/07/Image-4-2.png 568w, https://ohmyhome.com/wp-content/uploads/2021/07/Image-4-2-300x201.png 300w</value>
      <webElementGuid>b826d243-ae4b-4323-9508-90544a9b303b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-41666 page-child parent-pageid-7077 no-sidebar elementor-default elementor-template-canvas elementor-kit-6 elementor-page elementor-page-41666 elementor-page-51485 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-51485 elementor-location-single post-41666 page type-page status-publish hentry country-en-sg&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-40d7b841 elementor-section-full_width elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-7eacb482&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-2582c8ce elementor-widget elementor-widget-theme-post-content&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor elementor-41666&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-5aa3c4a elementor-section-boxed elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-210b66f&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-4c031df elementor-widget elementor-widget-text-editor&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;omh-elementor-page-wrap&quot;]/div[1]/div[@class=&quot;elementor elementor-11775&quot;]/div[@class=&quot;elementor-element elementor-element-770da29 e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-0d73c47 e-flex e-con-boxed e-con e-child&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-34144d9 elementor-widget__width-initial elementor-widget-mobile__width-inherit elementor-position-top elementor-widget elementor-widget-image-box&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor-image-box-wrapper&quot;]/figure[@class=&quot;elementor-image-box-img&quot;]/a[1]/img[@class=&quot;attachment-full size-full wp-image-11812 entered lazyloaded&quot;]</value>
      <webElementGuid>a5e9d261-1920-49a7-9cc9-9770f93d258c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://ohmyhome.com/wp-content/uploads/2021/07/Image-4-2.png')]</value>
      <webElementGuid>01394350-2e82-4102-9568-11ea41a21207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/div/div/figure/a/img</value>
      <webElementGuid>40dd0879-f6cf-48b3-a117-1b18098c3690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ohmyhome.com/wp-content/uploads/2021/07/Image-4-2.png']</value>
      <webElementGuid>52c154b5-ab09-4a5f-90a6-d97c59d1a9cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
