<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_attachment-full size-full wp-image-1180_6cde49</name>
   <tag></tag>
   <elementGuidId>9da5db49-51d5-473a-b3bd-09df2f86f785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://ohmyhome.com/wp-content/uploads/2021/07/Image-1-2.png')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-full.size-full.wp-image-11808.entered.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8c9377e1-1a8d-41c2-9933-7c05969c816b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>386025f8-f6c3-40fb-9cfc-ea6c8852d65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>ac3fd487-847f-40a9-aafb-2c46c7e889f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>568</value>
      <webElementGuid>2aa62e46-d790-43f6-b3b6-57e5219942ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>380</value>
      <webElementGuid>6f13dc9c-52a4-4435-8d01-18af523b8054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ohmyhome.com/wp-content/uploads/2021/07/Image-1-2.png</value>
      <webElementGuid>87139c83-b62d-4976-8823-f56ea027b26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-full size-full wp-image-11808 entered lazyloaded</value>
      <webElementGuid>9bab63f4-002c-4226-9129-a53f6a053662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-srcset</name>
      <type>Main</type>
      <value>https://ohmyhome.com/wp-content/uploads/2021/07/Image-1-2.png 568w, https://ohmyhome.com/wp-content/uploads/2021/07/Image-1-2-300x201.png 300w</value>
      <webElementGuid>041f0639-8260-4be2-af36-985c13920a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-sizes</name>
      <type>Main</type>
      <value>(max-width: 568px) 100vw, 568px</value>
      <webElementGuid>00db20c2-5e10-425d-9c41-4bbdc09c58f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://ohmyhome.com/wp-content/uploads/2021/07/Image-1-2.png</value>
      <webElementGuid>0e4f3d71-5bc4-4186-b911-e557d4f0bd2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>75fd4fb9-3457-49aa-b7ab-2217769d3d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 568px) 100vw, 568px</value>
      <webElementGuid>4552cfd0-26da-4c39-8d74-c41ae2d62068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://ohmyhome.com/wp-content/uploads/2021/07/Image-1-2.png 568w, https://ohmyhome.com/wp-content/uploads/2021/07/Image-1-2-300x201.png 300w</value>
      <webElementGuid>cf6ea75e-61c6-4b49-aa30-939de56a2337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-41666 page-child parent-pageid-7077 no-sidebar elementor-default elementor-template-canvas elementor-kit-6 elementor-page elementor-page-41666 elementor-page-51485 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-51485 elementor-location-single post-41666 page type-page status-publish hentry country-en-sg&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-40d7b841 elementor-section-full_width elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-7eacb482&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-2582c8ce elementor-widget elementor-widget-theme-post-content&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor elementor-41666&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-5aa3c4a elementor-section-boxed elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-210b66f&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-4c031df elementor-widget elementor-widget-text-editor&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;omh-elementor-page-wrap&quot;]/div[1]/div[@class=&quot;elementor elementor-11775&quot;]/div[@class=&quot;elementor-element elementor-element-4149fdc e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-edc30ba e-flex e-con-boxed e-con e-child&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-4ad6363 elementor-widget__width-initial elementor-widget-mobile__width-inherit elementor-position-top elementor-widget elementor-widget-image-box&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor-image-box-wrapper&quot;]/figure[@class=&quot;elementor-image-box-img&quot;]/a[1]/img[@class=&quot;attachment-full size-full wp-image-11808 entered lazyloaded&quot;]</value>
      <webElementGuid>175d98f5-2e43-4b10-adbe-d5c1ebd6a9bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://ohmyhome.com/wp-content/uploads/2021/07/Image-1-2.png')]</value>
      <webElementGuid>639c8eae-c566-4203-97ab-978c311bd72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>b784cead-c815-4692-8e8a-4ab0f334bef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ohmyhome.com/wp-content/uploads/2021/07/Image-1-2.png']</value>
      <webElementGuid>4e4ccd34-63a1-45c6-8d27-bb0695cb3226</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
