<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_voice recognition</name>
   <tag></tag>
   <elementGuidId>950315d9-aa62-443b-8b89-b9bc022c2e53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/p[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(4) > a.mw-redirect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>53ce8719-e96e-4d4a-bf75-c65c317236a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Voice_recognition_software</value>
      <webElementGuid>e30633c5-22d0-4b53-ba38-a16c446c8e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mw-redirect</value>
      <webElementGuid>6c7bb187-ba44-4cbc-845f-5021928c7465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>voice recognition</value>
      <webElementGuid>ebe497fa-4f96-40e5-a43a-513648265a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/p[4]/a[@class=&quot;mw-redirect&quot;]</value>
      <webElementGuid>8da5213c-3948-4244-988c-62773889a4e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/p[4]/a</value>
      <webElementGuid>9fc88f71-604a-45ba-9baa-af610102e3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'voice recognition')]</value>
      <webElementGuid>73ac6d06-607d-4163-a6e7-a2e21ac4d82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wiki/Voice_recognition_software')]</value>
      <webElementGuid>d44d2723-7d54-4bbd-aed4-2910e9fa72d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/a</value>
      <webElementGuid>e3f74b1b-4389-4b85-82e0-1bc74f463d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Voice_recognition_software' and (text() = 'voice recognition' or . = 'voice recognition')]</value>
      <webElementGuid>a37efef5-bc2b-48b2-8576-ffd116d01053</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
