<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CcAdNbmarginauto.QCzoEcmargin-top3pxcol_88446e</name>
   <tag></tag>
   <elementGuidId>f8a407d6-af49-4799-a821-c17126bed084</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.iblpc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>58d65a1b-bf2e-4592-a934-4e87e9f871f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iblpc</value>
      <webElementGuid>29fd5088-d948-4d14-90cb-f139b16a77a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>uFMOof</value>
      <webElementGuid>ed19e991-e4dc-4ced-9914-7b2604238693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>.CcAdNb{margin:auto}.QCzoEc{margin-top:3px;color:#9aa0a6}</value>
      <webElementGuid>702700ff-7ebe-484b-8205-e6c8dc3f04b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;L3eUgb&quot;]/div[@class=&quot;o3j99 ikrT4e om7nvf&quot;]/form[1]/div[1]/div[@class=&quot;A8SBwf emcav&quot;]/div[@class=&quot;RNNXgb&quot;]/div[@class=&quot;SDkEP&quot;]/div[@class=&quot;iblpc&quot;]</value>
      <webElementGuid>41d4fae1-7e8a-45ae-b5d6-18ef46ab2506</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div</value>
      <webElementGuid>e11bad38-4f42-4653-be6c-f14b4e2e63da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '.CcAdNb{margin:auto}.QCzoEc{margin-top:3px;color:#9aa0a6}' or . = '.CcAdNb{margin:auto}.QCzoEc{margin-top:3px;color:#9aa0a6}')]</value>
      <webElementGuid>dbe20dcd-fcdc-4cbd-bcbc-2934c80f1744</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
