<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_squid</name>
   <tag></tag>
   <elementGuidId>de4cbf39-4eb0-4d3c-8403-0a29d4873df8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Zrbbw']/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Zrbbw > div.wM6W7d > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>59719cb1-66a0-4127-9c18-bae9bb1887b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>squid</value>
      <webElementGuid>06a1fa42-38df-4397-8fde-1636941fc920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Zrbbw&quot;)/div[@class=&quot;wM6W7d&quot;]/span[1]</value>
      <webElementGuid>f8425845-cafa-4c22-b198-4b8d69c22c2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Zrbbw']/div/span</value>
      <webElementGuid>ccf8194d-2e90-44d9-bc63-2b7db924c62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li[4]/div/div[2]/div/div/span</value>
      <webElementGuid>e2cc371f-05e4-4c6a-8c92-b313ab156b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'squid' or . = 'squid')]</value>
      <webElementGuid>a7b96e5c-088a-4a26-8e48-fdbd9f35e6ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
