<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Animal</name>
   <tag></tag>
   <elementGuidId>50b3847c-11a8-4cdf-83cf-ea8868e9cd1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ERWdKc']/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ERWdKc > div.wM6W7d > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>637154f5-064b-43cc-9210-4464ec6357a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Animal</value>
      <webElementGuid>cab2c4ad-3e05-4ec0-a75f-fb06dcfe38e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ERWdKc&quot;)/div[@class=&quot;wM6W7d&quot;]/span[1]</value>
      <webElementGuid>b662ae4e-9535-474a-9fc4-3cc48337b96d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ERWdKc']/div/span</value>
      <webElementGuid>cda94f57-2038-40a1-8778-dca1e6d3728e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div[2]/div/div/span</value>
      <webElementGuid>08be4557-a2b2-40e0-b531-b39909362a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Animal' or . = 'Animal')]</value>
      <webElementGuid>db95e043-9e5d-4aae-add2-aa6a840164c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
