<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_monkey</name>
   <tag></tag>
   <elementGuidId>7693977f-a72c-4687-8515-f81804164ee9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ERWdKc']/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ERWdKc > div.wM6W7d > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>97708b42-3665-40e3-9077-08b5b0ccd464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>monkey</value>
      <webElementGuid>d690c55d-d83a-49e1-a914-cc0b0af4ac1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ERWdKc&quot;)/div[@class=&quot;wM6W7d&quot;]/span[1]</value>
      <webElementGuid>7d736786-44e6-4810-bd74-37d9202d22aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ERWdKc']/div/span</value>
      <webElementGuid>1998bdac-c13a-4f00-a20a-32ebe5c02f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div[2]/div/div/span</value>
      <webElementGuid>dc88963a-ad85-4afd-900c-be67e2634c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'monkey' or . = 'monkey')]</value>
      <webElementGuid>0e2a5244-2968-4bdb-aa6a-f9c0548b8389</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
