<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Zebra (American band)</name>
   <tag></tag>
   <elementGuidId>baa9e6c2-1917-4ef8-9c4e-b5f8a818953e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mw-content-ltr.mw-parser-output > ul > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d918c900-c48e-43aa-91a0-21bc6b0feb41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Zebra_(American_band)</value>
      <webElementGuid>da9c2d45-edf6-4126-a003-eebbf60188f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Zebra (American band)</value>
      <webElementGuid>4f8c91bc-d210-4d57-a210-d750952f02f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>d868cac1-a294-4042-8406-62d3279e4271</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/ul/li/a</value>
      <webElementGuid>ee5e5907-f430-4345-a103-4080be37f2a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Zebra (American band)')]</value>
      <webElementGuid>ea1b2f2e-fc68-4b1c-917c-f4c554839b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wiki/Zebra_(American_band)')]</value>
      <webElementGuid>23785848-734f-4f2b-a17a-0b6cc27cf901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/ul/li/a</value>
      <webElementGuid>05b78152-8c5f-474c-9ca9-79b5b67b4de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Zebra_(American_band)' and (text() = 'Zebra (American band)' or . = 'Zebra (American band)')]</value>
      <webElementGuid>3c5515fe-3d87-45df-bf3d-74187a5abbed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
