<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_aquatic ecosystems</name>
   <tag></tag>
   <elementGuidId>ff4e9603-46de-4dce-a5b2-4ba5d1f2d3a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/p[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(2) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>29619190-2a06-4e5d-a512-4c8f51e4d222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Aquatic_ecosystem</value>
      <webElementGuid>8bd4aa6b-b427-4063-ae95-187f2dfee79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>aquatic ecosystems</value>
      <webElementGuid>e69e4a72-5ff2-4aec-838a-207d25dec244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/p[2]/a[1]</value>
      <webElementGuid>8fd52fbd-462f-4f9e-92a5-804a3d0c6486</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/p[2]/a</value>
      <webElementGuid>3cd8ca23-63b7-4eda-ab3e-29d5b54948c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'aquatic ecosystems')]</value>
      <webElementGuid>4795cc7c-799a-4fc4-a5c7-6b87ed1c9f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wiki/Aquatic_ecosystem')]</value>
      <webElementGuid>91dfa998-83d8-4820-aec8-a5d1017d5e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
      <webElementGuid>ab5bcf42-2be6-4a54-8b56-da516260cdec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Aquatic_ecosystem' and (text() = 'aquatic ecosystems' or . = 'aquatic ecosystems')]</value>
      <webElementGuid>a2155601-4ea3-42fb-9256-7031b1eb696c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
