<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Location</name>
   <tag></tag>
   <elementGuidId>f1895d4e-3d1e-4867-9b51-e9dbf4f7fe88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.jsx-830412203.data</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f3edaf75-d99e-4d83-96c0-9da8d9dc855e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-830412203 data</value>
      <webElementGuid>13f50fc9-3c05-4818-a8b7-f8d726d79c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Location              </value>
      <webElementGuid>d1dd2562-873c-4e0a-97aa-68fdfe66f61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;n2webp&quot;]/body[@class=&quot;page-template-default page page-id-24891 page-parent page-child parent-pageid-7046 no-sidebar elementor-default elementor-template-canvas elementor-kit-6 elementor-page elementor-page-24891 elementor-page-51482 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-51482 elementor-location-single post-24891 page type-page status-publish hentry country-en-ph&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-3218ec4c elementor-section-full_width elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-38089b6d&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-48b6f8cc elementor-widget elementor-widget-theme-post-content&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor elementor-24891&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-256ddfbd elementor-section-boxed elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-2d101f47&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/section[@class=&quot;elementor-section elementor-inner-section elementor-element elementor-element-5758ea67 elementor-section-boxed elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-5452b13 elementor-hidden-tablet&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-72acc91 elementor-widget elementor-widget-html&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;jsx-830412203 header-container_bottom&quot;]/span[@class=&quot;jsx-830412203 null&quot;]/a[@class=&quot;jsx-830412203 link-item-container h-full relative block menu-1&quot;]/div[@class=&quot;jsx-830412203 data&quot;]</value>
      <webElementGuid>9135b099-3a97-46c3-aa96-f502e88a9354</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a/div</value>
      <webElementGuid>be1214f9-d51f-46c3-83ea-8ef840d01531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '  Location              ' or . = '  Location              ')]</value>
      <webElementGuid>346f5222-8b41-4605-8d2e-06118d8113c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
