<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Henry Thomas Davies</name>
   <tag></tag>
   <elementGuidId>27e9252b-dd31-40f7-b6fc-941b6b55ea73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/ul[2]/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul:nth-of-type(2) > li:nth-of-type(4) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b77fd95b-9341-4678-9eab-d0d8e94afe0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Henry_Thomas_Davies</value>
      <webElementGuid>1c8fe01d-71a9-47f9-ae81-4f70af117bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Henry Thomas Davies</value>
      <webElementGuid>45c6d615-9a85-43a9-b639-efff1aab34cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/ul[2]/li[4]/a[1]</value>
      <webElementGuid>3e25df23-60ca-4b88-aa58-08af0e1d84bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/ul[2]/li[4]/a</value>
      <webElementGuid>75e96680-b134-4104-b8df-8f783a099e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Henry Thomas Davies')]</value>
      <webElementGuid>47cf08ec-47cc-44fe-831a-5f28e1da57ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wiki/Henry_Thomas_Davies')]</value>
      <webElementGuid>ae332e9a-dbfc-4367-9d81-33cdd4266684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[4]/a</value>
      <webElementGuid>0c004f15-4de2-4dab-8da8-5ecc43c3b4c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Henry_Thomas_Davies' and (text() = 'Henry Thomas Davies' or . = 'Henry Thomas Davies')]</value>
      <webElementGuid>c20b477b-f653-4719-9379-a99681274ee3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
